import { AgregadoFamiliar, CaldoBase, Sopa } from './types';

export const CATEGORIAS_SOPAS = [
  'Termogénicas',
  'Saciantes',
  'Deshinchantes',
  'Cremosas Livianas',
];

export const CALDOS_BASE: CaldoBase[] = [
  {
    id: 1,
    numero: '01',
    nombre: 'Caldo Base de Vegetales',
    subtitulo: 'El Comodín Neutro',
    porciones: '6 porciones de 500 ml',
    ingredientes: [
      { categoria: 'Almacén', nombre: 'Agua', cantidad_base: 0.5, unidad: 'litro' },
      { categoria: 'Verdulería', nombre: 'Cebolla mediana', cantidad_base: 0.5, unidad: 'un' },
      { categoria: 'Verdulería', nombre: 'Puerro', cantidad_base: 0.33, unidad: 'un' },
      { categoria: 'Verdulería', nombre: 'Zanahoria', cantidad_base: 0.5, unidad: 'un' },
      { categoria: 'Verdulería', nombre: 'Apio', cantidad_base: 0.17, unidad: 'atado' },
      { categoria: 'Almacén', nombre: 'Laurel', cantidad_base: 0.33, unidad: 'hoja' },
      { categoria: 'Almacén', nombre: 'Granos de pimienta negra', cantidad_base: 0.17, unidad: 'cdita' },
    ],
    preparacion: [
      'En una olla grande, poné todos los ingredientes.',
      'Llevá a hervor, bajá el fuego a mínimo y cociná por 40 minutos.',
      'Colá y conservá solo el líquido.',
    ],
    usoIdeal: 'Tu lienzo base. Ideal para cualquier sopa crema donde no quieras alterar el sabor principal del vegetal protagonista.',
    valorNutricional: 'Aporta minerales esenciales y una base de sabor sutil que no compite con otros ingredientes.',
  },
  {
    id: 2,
    numero: '02',
    nombre: 'Caldo Base de Huesos',
    subtitulo: 'El Reparador Digestivo',
    porciones: '6 porciones de 500 ml',
    ingredientes: [
      { categoria: 'Almacén', nombre: 'Agua fría', cantidad_base: 0.5, unidad: 'litro' },
      { categoria: 'Carnicería', nombre: 'Huesos de vaca (osobuco o caracú)', cantidad_base: 0.17, unidad: 'kg' },
      { categoria: 'Verdulería', nombre: 'Zanahoria', cantidad_base: 0.17, unidad: 'un' },
      { categoria: 'Verdulería', nombre: 'Cebolla', cantidad_base: 0.17, unidad: 'un' },
      { categoria: 'Verdulería', nombre: 'Puerro', cantidad_base: 0.17, unidad: 'un' },
      { categoria: 'Almacén', nombre: 'Vinagre de manzana', cantidad_base: 0.17, unidad: 'cda' },
    ],
    preparacion: [
      'Colocá todo en la olla.',
      'Cociná a fuego mínimo (apenas burbujeando) entre 3 y 6 horas.',
      'Colá y dejá enfriar.',
    ],
    usoIdeal: 'El corazón de tus sopas más saciantes. Mantiene el estómago satisfecho por horas.',
    valorNutricional: 'Repara la mucosa intestinal y brinda una carga proteica de alta calidad y colágeno.',
  },
  {
    id: 3,
    numero: '03',
    nombre: 'Caldo Base de Pescado',
    subtitulo: 'El Liviano Refinado',
    porciones: '4 porciones de 500 ml',
    ingredientes: [
      { categoria: 'Almacén', nombre: 'Agua', cantidad_base: 0.5, unidad: 'litro' },
      { categoria: 'Pescadería', nombre: 'Espinas y cabezas de pescado blanco', cantidad_base: 0.25, unidad: 'kg' },
      { categoria: 'Verdulería', nombre: 'Cebolla', cantidad_base: 0.25, unidad: 'un' },
      { categoria: 'Verdulería', nombre: 'Puerro', cantidad_base: 0.25, unidad: 'un' },
      { categoria: 'Verdulería', nombre: 'Apio', cantidad_base: 0.25, unidad: 'tallo' },
      { categoria: 'Bebidas', nombre: 'Vino blanco', cantidad_base: 0.25, unidad: 'chorrito' },
      { categoria: 'Verdulería', nombre: 'Perejil fresco', cantidad_base: 0.25, unidad: 'puñado' },
    ],
    preparacion: [
      'Cociná a fuego suave por 25 minutos desde que rompe hervor.',
      'Colá inmediatamente para evitar amargor.',
    ],
    usoIdeal: 'Ideal para días de calor o cuando necesitás algo sumamente liviano pero con gran profundidad de sabor marino.',
    valorNutricional: 'Fuente de yodo y fósforo, de digestión extremadamente rápida.',
  },
  {
    id: 4,
    numero: '04',
    nombre: 'Caldo Base Funcional Deshinchante',
    subtitulo: 'Tu Herramienta de Rescate',
    porciones: '4 porciones de 500 ml',
    ingredientes: [
      { categoria: 'Almacén', nombre: 'Agua', cantidad_base: 0.5, unidad: 'litro' },
      { categoria: 'Verdulería', nombre: 'Apio (tallos y hojas)', cantidad_base: 0.5, unidad: 'atado' },
      { categoria: 'Verdulería', nombre: 'Perejil fresco', cantidad_base: 0.25, unidad: 'atado' },
      { categoria: 'Verdulería', nombre: 'Jengibre', cantidad_base: 0.25, unidad: 'rodaja gruesa' },
      { categoria: 'Verdulería', nombre: 'Ajo', cantidad_base: 0.5, unidad: 'diente' },
      { categoria: 'Verdulería', nombre: 'Hinojo picado', cantidad_base: 0.25, unidad: 'un' },
    ],
    preparacion: [
      'Herví todos los ingredientes durante 20 minutos a fuego suave.',
      'No lleva sal.',
    ],
    usoIdeal: 'Bebé una taza antes de cenar o usalo como base de sopas cuando notes retención de líquidos.',
    valorNutricional: 'Efecto diurético natural potente. Descongestiona el sistema linfático.',
  },
  {
    id: 5,
    numero: '05',
    nombre: 'Caldo Dorado Antiinflamatorio',
    porciones: '4 porciones de 500 ml',
    ingredientes: [
      { categoria: 'Preparaciones base', nombre: 'Caldo Base de Vegetales', cantidad_base: 0.5, unidad: 'litro' },
      { categoria: 'Verdulería', nombre: 'Cúrcuma fresca rallada', cantidad_base: 12.5, unidad: 'g' },
      { categoria: 'Almacén', nombre: 'Pimienta negra recién molida', cantidad_base: 0.25, unidad: 'cdita' },
    ],
    preparacion: [
      'Agregá la cúrcuma y la pimienta al caldo caliente.',
      'Dejá infusionar a fuego mínimo por 10 minutos sin hervir.',
    ],
    usoIdeal: 'Indicado para días post-esfuerzo físico o procesos inflamatorios.',
    valorNutricional: 'Reduce la inflamación sistémica. Es el caldo "renovador" por excelencia.',
  },
  {
    id: 6,
    numero: '06',
    nombre: 'Caldo de Recuperación Nocturna',
    subtitulo: 'El Inductor del Sueño',
    porciones: '4 porciones de 500 ml',
    ingredientes: [
      { categoria: 'Preparaciones base', nombre: 'Caldo Base de Huesos', cantidad_base: 0.5, unidad: 'litro' },
      { categoria: 'Almacén/Dietética', nombre: 'Semillas de zapallo', cantidad_base: 0.5, unidad: 'cda' },
      { categoria: 'Verdulería', nombre: 'Espinacas frescas', cantidad_base: 0.25, unidad: 'atado' },
    ],
    preparacion: [
      'Calentá el caldo, incorporá las espinacas y cociná 2 minutos.',
      'Retirá, añadí las semillas y procesá todo.',
    ],
    usoIdeal: 'Consumir una taza caliente una hora antes de dormir.',
    valorNutricional: 'Aporta magnesio y triptófano, facilitando el descanso profundo y reparador.',
  },
  {
    id: 7,
    numero: '07',
    nombre: 'Caldo de Algas',
    subtitulo: 'El Mineralizante',
    porciones: '4 porciones de 500 ml',
    ingredientes: [
      { categoria: 'Preparaciones base', nombre: 'Caldo Base de Vegetales', cantidad_base: 0.5, unidad: 'litro' },
      { categoria: 'Almacén/Dietética', nombre: 'Alga Kombu (aprox. 10 cm)', cantidad_base: 0.25, unidad: 'lámina' },
    ],
    preparacion: [
      'Dejá reposar el alga en el caldo frío 15 minutos.',
      'Luego, cociná 20 minutos a fuego suave.',
      'Retirá el alga antes de servir.',
    ],
    usoIdeal: 'Para cuando sientas fatiga mental o falta de energía sostenida.',
    valorNutricional: 'Alta densidad de minerales traza y yodo, fundamentales para la salud tiroidea.',
  },
  {
    id: 8,
    numero: '08',
    nombre: 'Caldo de Inmunidad',
    subtitulo: 'Escudo Natural',
    porciones: '4 porciones de 500 ml',
    ingredientes: [
      { categoria: 'Preparaciones base', nombre: 'Caldo Base de Huesos', cantidad_base: 0.5, unidad: 'litro' },
      { categoria: 'Verdulería', nombre: 'Ajo asado', cantidad_base: 1.5, unidad: 'dientes' },
      { categoria: 'Verdulería', nombre: 'Jengibre', cantidad_base: 0.75, unidad: 'rodajas gruesas' },
    ],
    preparacion: [
      'Incorporá el ajo asado y el jengibre al caldo caliente.',
      'Cociná a fuego mínimo por 15 minutos para integrar sabores.',
    ],
    usoIdeal: 'Consumir preventivamente en épocas de frío o ante los primeros síntomas de decaimiento.',
    valorNutricional: 'Potente efecto antiviral y antibacteriano. Fortalece la primera línea de defensa.',
  },
  {
    id: 9,
    numero: '09',
    nombre: 'Caldo de Setas',
    subtitulo: 'El Potenciador de Sabor / Umami',
    porciones: '4 porciones de 500 ml',
    ingredientes: [
      { categoria: 'Preparaciones base', nombre: 'Caldo Base de Vegetales', cantidad_base: 0.5, unidad: 'litro' },
      { categoria: 'Almacén/Dietética', nombre: 'Hongos secos (shiitake o porcini)', cantidad_base: 7.5, unidad: 'g' },
    ],
    preparacion: [
      'Hidratá los hongos en el caldo 30 minutos.',
      'Luego, cociná a fuego suave 20 minutos.',
      'Podés procesarlo o dejar los trozos.',
    ],
    usoIdeal: 'Cuando necesitás un plato con mucho cuerpo que inhiba el deseo de picotear.',
    valorNutricional: 'El umami natural envía señales directas de saciedad al cerebro.',
  },
  {
    id: 10,
    numero: '10',
    nombre: 'Caldo Verde Alcalinizante',
    porciones: '4 porciones de 500 ml',
    ingredientes: [
      { categoria: 'Preparaciones base', nombre: 'Caldo Base de Vegetales', cantidad_base: 0.5, unidad: 'litro' },
      { categoria: 'Verdulería', nombre: 'Cilantro', cantidad_base: 0.25, unidad: 'atado' },
      { categoria: 'Verdulería', nombre: 'Perejil', cantidad_base: 0.25, unidad: 'atado' },
      { categoria: 'Verdulería', nombre: 'Brócoli', cantidad_base: 25, unidad: 'g' },
    ],
    preparacion: [
      'Blanqueá el brócoli en el caldo 3 minutos.',
      'Retirá, agregá las hierbas frescas y procesá inmediatamente.',
    ],
    usoIdeal: 'Ideal para limpiar el organismo después de un fin de semana de excesos.',
    valorNutricional: 'Carga masiva de antioxidantes y clorofila para la detoxificación hepática.',
  },
];

export const AGREGADOS_FAMILIARES: AgregadoFamiliar[] = [
  {
    id: 1,
    numero: '01',
    nombre: 'Salchichas de copetín',
    cantidadSugerida: '50g',
    descripcion: 'Cocidas y cortadas en rodajas pequeñas.',
    tipPractico: 'Agrégalas al final para que mantengan su textura y no se desarmen en la sopa.',
    ingredientes: [
      { categoria: 'Carnicería', nombre: 'Salchichas de copetín', cantidad_base: 50, unidad: 'g' },
    ],
  },
  {
    id: 2,
    numero: '02',
    nombre: 'Jamón cocido natural',
    cantidadSugerida: '50g',
    descripcion: 'Cortado en tiritas finas o cubitos.',
    tipPractico: 'Es la proteína preferida de los niños por su sabor salado y textura suave.',
    ingredientes: [
      { categoria: 'Fiambrería', nombre: 'Jamón cocido natural', cantidad_base: 50, unidad: 'g' },
    ],
  },
  {
    id: 3,
    numero: '03',
    nombre: 'Huevo duro',
    cantidadSugerida: '1 unidad',
    descripcion: 'Picado groseramente.',
    tipPractico: 'Cociná 6 unidades el domingo y tenelas en la heladera; resuelven cualquier plato en segundos.',
    ingredientes: [
      { categoria: 'Almacén', nombre: 'Huevo', cantidad_base: 1, unidad: 'un' },
    ],
  },
  {
    id: 4,
    numero: '04',
    nombre: 'Queso cremoso',
    cantidadSugerida: '30g',
    descripcion: 'Un cubo generoso en el fondo del plato antes de servir.',
    tipPractico: 'El calor del caldo lo convierte en una crema fundida irresistible.',
    ingredientes: [
      { categoria: 'Lácteos', nombre: 'Queso cremoso', cantidad_base: 30, unidad: 'g' },
    ],
  },
  {
    id: 5,
    numero: '05',
    nombre: 'Muzzarella fresca',
    cantidadSugerida: '30g',
    descripcion: 'Cortada en cubitos pequeños.',
    tipPractico: 'Al contacto con la sopa muy caliente, genera ese efecto "hilo" de queso que fascina a los chicos.',
    ingredientes: [
      { categoria: 'Lácteos', nombre: 'Muzzarella fresca', cantidad_base: 30, unidad: 'g' },
    ],
  },
  {
    id: 6,
    numero: '06',
    nombre: 'Fideos cabello de ángel',
    cantidadSugerida: '40g en seco',
    descripcion: 'Cocidos aparte.',
    tipPractico: 'Son la clave para que la sopa "baje" bien en familias que aún no están acostumbradas a comer solo vegetales.',
    ingredientes: [
      { categoria: 'Almacén', nombre: 'Fideos cabello de ángel', cantidad_base: 40, unidad: 'g' },
    ],
  },
  {
    id: 7,
    numero: '07',
    nombre: 'Garbanzos cocidos',
    cantidadSugerida: '80g',
    descripcion: 'Lavados y escurridos.',
    tipPractico: 'Son ideales para sumar saciedad sin necesidad de cocinar carne; su textura firme acompaña muy bien las cremas.',
    ingredientes: [
      { categoria: 'Almacén', nombre: 'Garbanzos cocidos', cantidad_base: 80, unidad: 'g' },
    ],
  },
  {
    id: 8,
    numero: '08',
    nombre: 'Crema de leche',
    cantidadSugerida: '15ml / 1 cucharada sopera',
    descripcion: 'Un toque pequeño para cambiar la textura de sopas de vegetales.',
    tipPractico: 'Un toque pequeño es suficiente para cambiar la textura de cualquier sopa de vegetales y hacerla más aceptable para paladares infantiles.',
    ingredientes: [
      { categoria: 'Lácteos', nombre: 'Crema de leche', cantidad_base: 15, unidad: 'ml' },
    ],
  },
  {
    id: 9,
    numero: '09',
    nombre: 'Queso tipo Tybo/Dambo',
    cantidadSugerida: '30g',
    descripcion: 'Cortado en cubitos o tiritas.',
    tipPractico: 'Si usás una tostada de pan integral, poné el queso encima y gratinalo brevemente para un efecto "sopa gratinada".',
    ingredientes: [
      { categoria: 'Lácteos', nombre: 'Queso tipo Tybo/Dambo', cantidad_base: 30, unidad: 'g' },
    ],
  },
  {
    id: 10,
    numero: '10',
    nombre: 'Carne picada magra',
    cantidadSugerida: '150g',
    descripcion: 'Salteada previamente con ajo y pimentón.',
    tipPractico: 'Es tu mayor aliado de batch cooking; congelá porciones individuales de 150g y tenelas siempre listas.',
    ingredientes: [
      { categoria: 'Carnicería', nombre: 'Carne picada magra', cantidad_base: 150, unidad: 'g' },
    ],
  },
  {
    id: 11,
    numero: '11',
    nombre: 'Atún al natural',
    cantidadSugerida: '1/2 lata - 60g',
    descripcion: 'Bien escurrido.',
    tipPractico: 'Es la proteína más rápida de la alacena, ideal para cuando llegás cansada y necesitás algo listo en 1 minuto.',
    ingredientes: [
      { categoria: 'Almacén', nombre: 'Atún al natural', cantidad_base: 0.5, unidad: 'lata' },
    ],
  },
  {
    id: 12,
    numero: '12',
    nombre: 'Lentejas en conserva',
    cantidadSugerida: '80g',
    descripcion: 'Lavadas bajo el chorro de agua fría.',
    tipPractico: 'Su aporte de fibra es masivo; aumentan la densidad del plato y eliminan el hambre por completo.',
    ingredientes: [
      { categoria: 'Almacén', nombre: 'Lentejas en conserva', cantidad_base: 80, unidad: 'g' },
    ],
  },
  {
    id: 13,
    numero: '13',
    nombre: 'Pechuga de pollo desmechada',
    cantidadSugerida: '150g',
    descripcion: 'Base proteica magra para sumar directamente al plato.',
    tipPractico: 'Cociná un pollo entero el fin de semana, desmechalo y freezalo en porciones de 150g. Es la base proteica más magra y versátil.',
    ingredientes: [
      { categoria: 'Carnicería', nombre: 'Pechuga de pollo desmechada', cantidad_base: 150, unidad: 'g' },
    ],
  },
  {
    id: 14,
    numero: '14',
    nombre: 'Huevo poché',
    cantidadSugerida: '1 unidad',
    descripcion: 'Cocinado 2 minutos en el microondas dentro de una taza con agua.',
    tipPractico: 'El toque de yema líquida añade una cremosidad natural que eleva cualquier sopa simple a plato gourmet.',
    ingredientes: [
      { categoria: 'Almacén', nombre: 'Huevo', cantidad_base: 1, unidad: 'un' },
    ],
  },
  {
    id: 15,
    numero: '15',
    nombre: 'Semillas de sésamo o girasol',
    cantidadSugerida: '10g',
    descripcion: 'Terminación crocante para sumar al servir.',
    tipPractico: 'Tostalas apenas en una sartén seca antes de agregar; el aroma que liberan estimula el apetito y añade un toque crocante necesario para la saciedad mental.',
    ingredientes: [
      { categoria: 'Almacén/Dietética', nombre: 'Semillas de sésamo o girasol', cantidad_base: 10, unidad: 'g' },
    ],
  },
  {
    id: 16,
    numero: '16',
    nombre: 'Espinaca fresca',
    cantidadSugerida: '1 puñado grande',
    descripcion: 'Agregado vegetal fresco para terminar la sopa.',
    tipPractico: 'Agregala apenas apagues el fuego; el calor residual la cocina en segundos manteniendo todas sus vitaminas y color vibrante.',
    ingredientes: [
      { categoria: 'Verdulería', nombre: 'Espinaca fresca', cantidad_base: 1, unidad: 'puñado grande' },
    ],
  },
  {
    id: 17,
    numero: '17',
    nombre: 'Vitina o sémola',
    cantidadSugerida: '20g en seco',
    descripcion: 'Recurso para espesar caldos de forma rápida.',
    tipPractico: 'Es un recurso excelente para espesar caldos de forma rápida para los chicos, aportando energía de absorción lenta.',
    ingredientes: [
      { categoria: 'Almacén', nombre: 'Vitina o sémola', cantidad_base: 20, unidad: 'g' },
    ],
  },
  {
    id: 18,
    numero: '18',
    nombre: 'Fideos municiones',
    cantidadSugerida: '40g en seco',
    descripcion: 'Pasta pequeña para sumar a sopas familiares.',
    tipPractico: 'Por su tamaño pequeño, son ideales para que los niños los identifiquen y acepten mejor la sopa sin que parezca un plato de pasta pesada.',
    ingredientes: [
      { categoria: 'Almacén', nombre: 'Fideos municiones', cantidad_base: 40, unidad: 'g' },
    ],
  },
];

export const SOPAS: Sopa[] = [
  {
    id: 1,
    numero: '01',
    nombre: 'Crema de Zapallo y Jengibre',
    subtitulo: 'El clásico activador',
    categoria_sopa: 'Termogénicas',
    caldo_base_sugerido_id: 1,
    porciones: '3 a 4',
    porcionesBase: 4,
    ingredientes: [
      { categoria: 'Verdulería', nombre: 'Zapallo anco mediano pelado y en cubos', cantidad_base: 0.5, unidad: 'un' },
      { categoria: 'Verdulería', nombre: 'Cebolla grande', cantidad_base: 1, unidad: 'un' },
      { categoria: 'Verdulería', nombre: 'Jengibre fresco pelado', cantidad_base: 1, unidad: 'rodaja' },
      { categoria: 'Preparaciones base', nombre: 'Caldo Base de Vegetales', cantidad_base: 1, unidad: 'litro' },
      { categoria: 'Almacén', nombre: 'Sal', cantidad_base: 1, unidad: 'pizca' },
      { categoria: 'Almacén', nombre: 'Pimienta negra', cantidad_base: 1, unidad: 'pizca' },
      { categoria: 'Almacén', nombre: 'Aceite de oliva', cantidad_base: 1, unidad: 'chorrito' },
    ],
    pasos_preparacion: [
      { titulo: 'Paso 1', descripcion: 'En la olla, rehogá la cebolla picada gruesa con un hilito de aceite y un chorrito de agua para que no se pegue.' },
      { titulo: 'Paso 2', descripcion: 'Cuando esté transparente, agregá el zapallo y el jengibre entero.' },
      { titulo: 'Paso 3', descripcion: 'Volcá el caldo de vegetales hasta cubrir todo. Cociná a fuego medio, tapado, por unos 25 minutos o hasta que el zapallo esté súper tierno al pincharlo.' },
      { titulo: 'Paso 4', descripcion: 'Apagá el fuego, agregá la pimienta negra y procesá todo con minipimer o licuadora hasta lograr una crema bien lisa.' },
    ],
    tip: 'Si usás jengibre en polvo, agregalo recién al final de la cocción (media cucharadita).',
  },
  {
    id: 2,
    numero: '02',
    nombre: 'Sopa de Repollo, Cúrcuma y Verdeo',
    subtitulo: 'Barrido profundo',
    categoria_sopa: 'Termogénicas',
    caldo_base_sugerido_id: 2,
    notaCaldoBase: 'La receta permite caldo base de hueso o vegetales; se recomienda el primero mencionado.',
    porciones: '4',
    porcionesBase: 4,
    ingredientes: [
      { categoria: 'Verdulería', nombre: 'Repollo blanco chico en tiritas finas', cantidad_base: 0.5, unidad: 'un' },
      { categoria: 'Verdulería', nombre: 'Cebolla de verdeo', cantidad_base: 2, unidad: 'ramas' },
      { categoria: 'Verdulería', nombre: 'Zanahoria rallada', cantidad_base: 1, unidad: 'un' },
      { categoria: 'Almacén', nombre: 'Cúrcuma en polvo', cantidad_base: 1, unidad: 'cdita generosa' },
      { categoria: 'Almacén', nombre: 'Pimienta negra', cantidad_base: 1, unidad: 'pizca' },
      { categoria: 'Preparaciones base', nombre: 'Caldo Base de Huesos', cantidad_base: 1.5, unidad: 'litros' },
    ],
    pasos_preparacion: [
      { titulo: 'Paso 1', descripcion: 'Picá el verdeo y doralo un par de minutos en la olla.' },
      { titulo: 'Paso 2', descripcion: 'Sumá la zanahoria rallada y el repollo en tiritas. Revolvé un poco hasta que el repollo empiece a achicarse.' },
      { titulo: 'Paso 3', descripcion: 'Condimentá con la cúrcuma y la pimienta, mezclá bien para que las verduras tomen color, y cubrí con el caldo caliente.' },
      { titulo: 'Paso 4', descripcion: 'Cociná a fuego bajo por unos 30 minutos. El repollo tiene que quedar casi transparente y súper suave. Esta sopa no se procesa, se come así, bien contundente.' },
    ],
  },
  {
    id: 3,
    numero: '03',
    nombre: 'Caldo Rojo de Tomate, Morrón y Ají',
    subtitulo: 'Termogénesis rápida',
    categoria_sopa: 'Termogénicas',
    caldo_base_sugerido_id: 1,
    porciones: '2 a 3',
    porcionesBase: 3,
    ingredientes: [
      { categoria: 'Verdulería', nombre: 'Tomates perita maduros cubeteados', cantidad_base: 4, unidad: 'un' },
      { categoria: 'Verdulería', nombre: 'Morrón rojo', cantidad_base: 0.5, unidad: 'un' },
      { categoria: 'Verdulería', nombre: 'Ajo', cantidad_base: 1, unidad: 'diente' },
      { categoria: 'Almacén', nombre: 'Ají molido', cantidad_base: 0.5, unidad: 'cdita' },
      { categoria: 'Preparaciones base', nombre: 'Caldo Base de Vegetales', cantidad_base: 1, unidad: 'litro' },
    ],
    pasos_preparacion: [
      { titulo: 'Paso 1', descripcion: 'Poné el morrón en cubos y el diente de ajo en la olla con un chorrito de agua o caldo.' },
      { titulo: 'Paso 2', descripcion: 'Sumá los tomates, el ají molido y cubrí con el resto del caldo.' },
      { titulo: 'Paso 3', descripcion: 'Herví por 20 minutos. El tomate se va a deshacer casi por completo.' },
      { titulo: 'Paso 4', descripcion: 'Podés tomarla así (como un caldo con tropezones) o procesarla apenas para que quede como un jugo caliente y espeso.' },
    ],
  },
  {
    id: 4,
    numero: '04',
    nombre: 'Crema Verde al Curry',
    subtitulo: 'Desintoxicante con calor',
    categoria_sopa: 'Termogénicas',
    caldo_base_sugerido_id: 1,
    notaCaldoBase: 'La receta permite caldo base de vegetales o caldo funcional deshinchante; se recomienda el primero mencionado.',
    porciones: '3 a 4',
    porcionesBase: 4,
    ingredientes: [
      { categoria: 'Verdulería', nombre: 'Espinaca lavada', cantidad_base: 1, unidad: 'atado grande' },
      { categoria: 'Verdulería', nombre: 'Zapallitos verdes medianos en cubos', cantidad_base: 2, unidad: 'un' },
      { categoria: 'Verdulería', nombre: 'Cebolla chica', cantidad_base: 1, unidad: 'un' },
      { categoria: 'Almacén', nombre: 'Polvo curry', cantidad_base: 1, unidad: 'cda al ras' },
      { categoria: 'Preparaciones base', nombre: 'Caldo Base de Vegetales', cantidad_base: 1, unidad: 'litro' },
    ],
    pasos_preparacion: [
      { titulo: 'Paso 1', descripcion: 'Rehogá la cebolla junto con los zapallitos.' },
      { titulo: 'Paso 2', descripcion: 'Cuando ablanden un poco, espolvoreá el curry y revolvé rápido para que las especias se tuesten apenas.' },
      { titulo: 'Paso 3', descripcion: 'Agregá el caldo y dejá cocinar 15 minutos.' },
      { titulo: 'Paso 4', descripcion: 'En el último minuto de cocción, agregá las hojas de espinaca frescas.' },
      { titulo: 'Paso 5', descripcion: 'Apagá el fuego y procesá todo hasta lograr una crema verde brillante y aromática.' },
    ],
  },
  {
    id: 5,
    numero: '05',
    nombre: 'Crema de Zanahoria, Naranja y Jengibre',
    subtitulo: 'Escudo protector',
    categoria_sopa: 'Termogénicas',
    caldo_base_sugerido_id: 1,
    porciones: '3',
    porcionesBase: 3,
    ingredientes: [
      { categoria: 'Verdulería', nombre: 'Zanahorias grandes en rueditas', cantidad_base: 4, unidad: 'un' },
      { categoria: 'Verdulería', nombre: 'Cebolla', cantidad_base: 1, unidad: 'un' },
      { categoria: 'Verdulería', nombre: 'Jengibre fresco pelado', cantidad_base: 1, unidad: 'rodaja' },
      { categoria: 'Verdulería', nombre: 'Naranja dulce', cantidad_base: 0.5, unidad: 'un' },
      { categoria: 'Preparaciones base', nombre: 'Caldo Base de Vegetales', cantidad_base: 1, unidad: 'litro' },
    ],
    pasos_preparacion: [
      { titulo: 'Paso 1', descripcion: 'Rehogá apenas la cebolla y la zanahoria en la olla.' },
      { titulo: 'Paso 2', descripcion: 'Agregá el jengibre entero y volcá el caldo.' },
      { titulo: 'Paso 3', descripcion: 'Herví 20 minutos hasta que la zanahoria esté muy tierna al pincharla.' },
      { titulo: 'Paso 4', descripcion: 'Apagá el fuego, sumá el jugo de naranja recién exprimido y procesá con minipimer hasta que quede una crema sedosa.' },
    ],
  },
  {
    id: 6,
    numero: '06',
    nombre: 'Caldo Vigoroso de Hueso y Ajo Asado',
    subtitulo: 'Dulzor circulatorio',
    categoria_sopa: 'Termogénicas',
    caldo_base_sugerido_id: 2,
    porciones: '2',
    porcionesBase: 2,
    ingredientes: [
      { categoria: 'Verdulería', nombre: 'Ajo', cantidad_base: 1, unidad: 'cabeza' },
      { categoria: 'Verdulería', nombre: 'Cebolla de verdeo', cantidad_base: 2, unidad: 'ramas' },
      { categoria: 'Almacén', nombre: 'Pimienta negra', cantidad_base: 1, unidad: 'pizca' },
      { categoria: 'Preparaciones base', nombre: 'Caldo Base de Huesos', cantidad_base: 1, unidad: 'litro' },
    ],
    pasos_preparacion: [
      { titulo: 'Paso 1', descripcion: 'Envolvé la cabeza de ajo entera (sin pelar) en papel aluminio y horneala 30 minutos a fuego medio.' },
      { titulo: 'Paso 2', descripcion: 'Cortá la base de la cabeza de ajo asada y exprimí el puré de ajo dulce directo en una olla.' },
      { titulo: 'Paso 3', descripcion: 'Volcá el caldo de hueso, agregá la pimienta, revolvé bien para integrar el puré y calentá hasta que rompa hervor.' },
      { titulo: 'Paso 4', descripcion: 'Serví en tazones con el verdeo fresco por arriba.' },
    ],
  },
  {
    id: 7,
    numero: '07',
    nombre: 'Crema de Coliflor y Mostaza',
    subtitulo: 'Calor profundo',
    categoria_sopa: 'Termogénicas',
    caldo_base_sugerido_id: 1,
    porciones: '4',
    porcionesBase: 4,
    ingredientes: [
      { categoria: 'Verdulería', nombre: 'Coliflor chica separada en arbolitos', cantidad_base: 1, unidad: 'planta' },
      { categoria: 'Verdulería', nombre: 'Puerro grande', cantidad_base: 1, unidad: 'un' },
      { categoria: 'Almacén', nombre: 'Mostaza', cantidad_base: 1, unidad: 'cda' },
      { categoria: 'Preparaciones base', nombre: 'Caldo Base de Vegetales', cantidad_base: 1, unidad: 'litro' },
    ],
    pasos_preparacion: [
      { titulo: 'Paso 1', descripcion: 'Dorá apenas el puerro picado en la olla.' },
      { titulo: 'Paso 2', descripcion: 'Agregá los arbolitos de coliflor y volcá el caldo de vegetales.' },
      { titulo: 'Paso 3', descripcion: 'Cociná 15 minutos hasta que el coliflor esté blando.' },
      { titulo: 'Paso 4', descripcion: 'Apagá el fuego, agregá la cucharada de mostaza, mezclá bien y procesá hasta que quede súper cremosa.' },
    ],
  },
  {
    id: 8,
    numero: '08',
    nombre: 'Sopa Intensa de Morrón Asado y Pimentón',
    subtitulo: 'Ahumado ligero',
    categoria_sopa: 'Termogénicas',
    caldo_base_sugerido_id: 2,
    notaCaldoBase: 'La receta permite caldo base de hueso o de vegetales; se recomienda el primero mencionado.',
    porciones: '3',
    porcionesBase: 3,
    ingredientes: [
      { categoria: 'Verdulería', nombre: 'Morrones rojos grandes', cantidad_base: 2, unidad: 'un' },
      { categoria: 'Verdulería', nombre: 'Cebolla blanca', cantidad_base: 1, unidad: 'un' },
      { categoria: 'Almacén', nombre: 'Pimentón dulce o ahumado', cantidad_base: 1, unidad: 'cdita colmada' },
      { categoria: 'Preparaciones base', nombre: 'Caldo Base de Huesos', cantidad_base: 1, unidad: 'litro' },
    ],
    pasos_preparacion: [
      { titulo: 'Paso 1', descripcion: 'Quemá los morrones enteros en la hornalla directa o al horno fuerte hasta que la piel esté negra.' },
      { titulo: 'Paso 2', descripcion: 'Pelalos, sacales las semillas y cortalos en tiras gruesas.' },
      { titulo: 'Paso 3', descripcion: 'Rehogá la cebolla, sumá el morrón asado, espolvoreá el pimentón y revolvé.' },
      { titulo: 'Paso 4', descripcion: 'Agregá el caldo, cociná 10 minutos para unificar sabores y procesá.' },
    ],
  },
  {
    id: 9,
    numero: '09',
    nombre: 'Caldo Termogénico de Pescado al Limón',
    subtitulo: 'Digestión rápida',
    categoria_sopa: 'Termogénicas',
    caldo_base_sugerido_id: 3,
    porciones: '2',
    porcionesBase: 2,
    ingredientes: [
      { categoria: 'Verdulería', nombre: 'Jengibre rallado', cantidad_base: 1, unidad: 'cda' },
      { categoria: 'Verdulería', nombre: 'Limón fresco', cantidad_base: 1, unidad: 'un' },
      { categoria: 'Almacén', nombre: 'Ají molido o pimienta negra', cantidad_base: 1, unidad: 'pizca' },
      { categoria: 'Verdulería', nombre: 'Cilantro o perejil fresco picado', cantidad_base: 1, unidad: 'puñado' },
      { categoria: 'Preparaciones base', nombre: 'Caldo Base de Pescado', cantidad_base: 1, unidad: 'litro' },
    ],
    pasos_preparacion: [
      { titulo: 'Paso 1', descripcion: 'Calentá el caldo de pescado en la olla junto con el jengibre rallado y el ají molido.' },
      { titulo: 'Paso 2', descripcion: 'Dejá que rompa hervor, cociná 2 minutos para que infusione y apagá.' },
      { titulo: 'Paso 3', descripcion: 'Agregá el jugo de limón y el perejil o cilantro fresco directo en la olla justo antes de servir en los platos.' },
    ],
  },
  {
    id: 10,
    numero: '10',
    nombre: 'Crema de Brócoli a la Pimienta Blanca',
    subtitulo: 'Saciedad térmica',
    categoria_sopa: 'Termogénicas',
    caldo_base_sugerido_id: 1,
    porciones: '4',
    porcionesBase: 4,
    ingredientes: [
      { categoria: 'Verdulería', nombre: 'Brócoli', cantidad_base: 1, unidad: 'planta' },
      { categoria: 'Verdulería', nombre: 'Cebolla blanca', cantidad_base: 1, unidad: 'un' },
      { categoria: 'Almacén', nombre: 'Pimienta blanca molida', cantidad_base: 0.5, unidad: 'cdita' },
      { categoria: 'Preparaciones base', nombre: 'Caldo Base de Vegetales', cantidad_base: 1, unidad: 'litro' },
    ],
    pasos_preparacion: [
      { titulo: 'Paso 1', descripcion: 'Rehogá la cebolla picada hasta que esté blanda.' },
      { titulo: 'Paso 2', descripcion: 'Sumá el brócoli en trozos y cubrí con el caldo.' },
      { titulo: 'Paso 3', descripcion: 'Cociná 15 minutos exactos a fuego medio (no más, para que el brócoli no pierda su color verde brillante).' },
      { titulo: 'Paso 4', descripcion: 'Condimentá con la pimienta blanca y procesá todo hasta formar una crema.' },
    ],
  },
  {
    id: 11,
    numero: '11',
    nombre: 'Sopa Picante de Zapallito y Cebolla Morada',
    subtitulo: 'Carácter fuerte',
    categoria_sopa: 'Termogénicas',
    caldo_base_sugerido_id: 4,
    porciones: '3',
    porcionesBase: 3,
    ingredientes: [
      { categoria: 'Verdulería', nombre: 'Zapallitos verdes en cubos', cantidad_base: 4, unidad: 'un' },
      { categoria: 'Verdulería', nombre: 'Cebollas moradas picadas', cantidad_base: 2, unidad: 'un' },
      { categoria: 'Almacén', nombre: 'Ají molido', cantidad_base: 1, unidad: 'cdita' },
      { categoria: 'Preparaciones base', nombre: 'Caldo Base Funcional Deshinchante', cantidad_base: 1, unidad: 'litro' },
    ],
    pasos_preparacion: [
      { titulo: 'Paso 1', descripcion: 'Rehogá la cebolla morada con un chorrito de agua o caldo hasta que esté blanda y transparente.' },
      { titulo: 'Paso 2', descripcion: 'Agregá el ají molido y mezclá para que libere su aroma.' },
      { titulo: 'Paso 3', descripcion: 'Sumá los zapallitos y el caldo. Cociná 15 minutos.' },
      { titulo: 'Paso 4', descripcion: 'Podés tomarla así, rústica con los trozos enteros, o procesarla.' },
    ],
  },
  {
    id: 12,
    numero: '12',
    nombre: 'Crema Dorada de Apio y Cúrcuma',
    subtitulo: 'Diurético potente',
    categoria_sopa: 'Termogénicas',
    caldo_base_sugerido_id: 1,
    porciones: '3',
    porcionesBase: 3,
    ingredientes: [
      { categoria: 'Verdulería', nombre: 'Apio lavado y picado', cantidad_base: 1, unidad: 'planta' },
      { categoria: 'Verdulería', nombre: 'Cebolla', cantidad_base: 1, unidad: 'un' },
      { categoria: 'Almacén', nombre: 'Cúrcuma en polvo', cantidad_base: 1, unidad: 'cda' },
      { categoria: 'Almacén', nombre: 'Pimienta negra', cantidad_base: 1, unidad: 'pizca' },
      { categoria: 'Preparaciones base', nombre: 'Caldo Base de Vegetales', cantidad_base: 1, unidad: 'litro' },
    ],
    pasos_preparacion: [
      { titulo: 'Paso 1', descripcion: 'Rehogá la cebolla y el apio picado en la olla.' },
      { titulo: 'Paso 2', descripcion: 'Cuando ablanden, sumá la cúrcuma y la pimienta, integrando bien.' },
      { titulo: 'Paso 3', descripcion: 'Volcá el caldo y cociná por 20 minutos.' },
      { titulo: 'Paso 4', descripcion: 'Procesá muy bien (el apio tiene fibras duras, así que procesá un minuto extra para asegurar una textura perfectamente sedosa).' },
    ],
  },
  {
    id: 13,
    numero: '13',
    nombre: 'Caldo Fuerte de Chauchas y Ajo',
    subtitulo: 'Trabajo suave',
    categoria_sopa: 'Termogénicas',
    caldo_base_sugerido_id: 2,
    porciones: '2 a 3',
    porcionesBase: 3,
    ingredientes: [
      { categoria: 'Verdulería', nombre: 'Chauchas frescas lavadas y cortadas', cantidad_base: 400, unidad: 'g' },
      { categoria: 'Verdulería', nombre: 'Ajo en láminas finas', cantidad_base: 3, unidad: 'dientes' },
      { categoria: 'Preparaciones base', nombre: 'Caldo Base de Huesos', cantidad_base: 1, unidad: 'litro' },
      { categoria: 'Almacén', nombre: 'Aceite', cantidad_base: 1, unidad: 'hilo mínimo' },
    ],
    pasos_preparacion: [
      { titulo: 'Paso 1', descripcion: 'En la olla, dorá apenas las láminas de ajo con un mínimo hilo de aceite. Atención: que no se quemen porque amargan toda la sopa.' },
      { titulo: 'Paso 2', descripcion: 'Enseguida sumá las chauchas cortadas y revolvé un minuto.' },
      { titulo: 'Paso 3', descripcion: 'Volcá el caldo caliente, tapá la olla y cociná 15 minutos hasta que las chauchas estén tiernas. Serví sin procesar.' },
    ],
  },
  {
    id: 14,
    numero: '14',
    nombre: 'Sopa de Tomate, Ajo y Albahaca Caliente',
    subtitulo: 'Vasodilatador natural',
    categoria_sopa: 'Termogénicas',
    caldo_base_sugerido_id: 1,
    porciones: '3',
    porcionesBase: 3,
    ingredientes: [
      { categoria: 'Almacén', nombre: 'Tomates perita en lata', cantidad_base: 1, unidad: 'lata' },
      { categoria: 'Verdulería', nombre: 'Ajo pelado', cantidad_base: 4, unidad: 'dientes' },
      { categoria: 'Verdulería', nombre: 'Albahaca fresca', cantidad_base: 1, unidad: 'puñado generoso' },
      { categoria: 'Almacén', nombre: 'Pimienta negra', cantidad_base: 1, unidad: 'pizca' },
      { categoria: 'Preparaciones base', nombre: 'Caldo Base de Vegetales', cantidad_base: 1, unidad: 'litro' },
    ],
    pasos_preparacion: [
      { titulo: 'Paso 1', descripcion: 'Poné los tomates, los dientes de ajo enteros y la pimienta en la olla junto con el caldo.' },
      { titulo: 'Paso 2', descripcion: 'Herví a fuego medio por 20 minutos hasta que el ajo esté blandísimo.' },
      { titulo: 'Paso 3', descripcion: 'Procesá todo en la misma olla.' },
      { titulo: 'Paso 4', descripcion: 'Antes de servir, rompé las hojas de albahaca fresca con la mano (no con cuchillo) y tiralas sobre la sopa bien caliente para que liberen su aceite esencial.' },
    ],
  },
  {
    id: 15,
    numero: '15',
    nombre: 'Crema de Puerro, Nuez Moscada y Jengibre',
    subtitulo: 'Confort hogareño',
    categoria_sopa: 'Termogénicas',
    caldo_base_sugerido_id: 1,
    porciones: '4',
    porcionesBase: 4,
    ingredientes: [
      { categoria: 'Verdulería', nombre: 'Puerros grandes picados', cantidad_base: 4, unidad: 'un' },
      { categoria: 'Verdulería', nombre: 'Jengibre fresco', cantidad_base: 1, unidad: 'rodaja fina' },
      { categoria: 'Almacén', nombre: 'Nuez moscada recién rallada', cantidad_base: 0.5, unidad: 'cdita' },
      { categoria: 'Preparaciones base', nombre: 'Caldo Base de Vegetales', cantidad_base: 1, unidad: 'litro' },
    ],
    pasos_preparacion: [
      { titulo: 'Paso 1', descripcion: 'Cortá los puerros en rueditas finas y doralos lentamente en la olla hasta que estén tiernos.' },
      { titulo: 'Paso 2', descripcion: 'Sumá el jengibre entero y volcá el caldo.' },
      { titulo: 'Paso 3', descripcion: 'Cociná por 20 minutos a fuego bajo.' },
      { titulo: 'Paso 4', descripcion: 'Retirá la olla del fuego, agregá la nuez moscada rallada y procesá hasta obtener una crema espesa.' },
    ],
  },
  {
    id: 16,
    numero: '16',
    nombre: 'Crema Rústica de Zapallo y Zanahoria',
    subtitulo: 'Doble fibra',
    categoria_sopa: 'Saciantes',
    caldo_base_sugerido_id: 1,
    porciones: '4',
    porcionesBase: 4,
    ingredientes: [
      { categoria: 'Verdulería', nombre: 'Zapallo anco grande pelado y en cubos gruesos', cantidad_base: 0.5, unidad: 'un' },
      { categoria: 'Verdulería', nombre: 'Zanahorias grandes en rueditas', cantidad_base: 3, unidad: 'un' },
      { categoria: 'Verdulería', nombre: 'Cebolla blanca', cantidad_base: 1, unidad: 'un' },
      { categoria: 'Preparaciones base', nombre: 'Caldo Base de Vegetales', cantidad_base: 1, unidad: 'litro' },
      { categoria: 'Almacén', nombre: 'Sal', cantidad_base: 1, unidad: 'pizca' },
      { categoria: 'Almacén', nombre: 'Pimienta', cantidad_base: 1, unidad: 'pizca' },
      { categoria: 'Almacén', nombre: 'Aceite de oliva', cantidad_base: 1, unidad: 'hilo' },
    ],
    pasos_preparacion: [
      { titulo: 'Paso 1', descripcion: 'Rehogá la cebolla picada con un mínimo de aceite y agua.' },
      { titulo: 'Paso 2', descripcion: 'Sumá la zanahoria y el zapallo, revolviendo por un par de minutos para que tomen calor.' },
      { titulo: 'Paso 3', descripcion: 'Volcá el caldo de vegetales y cociná a fuego medio por 25 minutos.' },
      { titulo: 'Paso 4', descripcion: 'Con un pisapapas (en lugar de la minipimer), pisá las verduras directo en la olla. Te va a quedar una crema rústica con pequeños trozos enteros, ideal para masticar.' },
    ],
  },
  {
    id: 17,
    numero: '17',
    nombre: 'Sopa Contundente de Repollo y Champiñones',
    subtitulo: 'Masticación extra',
    categoria_sopa: 'Saciantes',
    caldo_base_sugerido_id: 2,
    porciones: '3',
    porcionesBase: 3,
    ingredientes: [
      { categoria: 'Verdulería', nombre: 'Repollo blanco en tiritas', cantidad_base: 0.5, unidad: 'un' },
      { categoria: 'Verdulería', nombre: 'Champiñones frescos fileteados', cantidad_base: 200, unidad: 'g' },
      { categoria: 'Verdulería', nombre: 'Cebolla de verdeo', cantidad_base: 2, unidad: 'ramas' },
      { categoria: 'Preparaciones base', nombre: 'Caldo Base de Huesos', cantidad_base: 1, unidad: 'litro' },
    ],
    pasos_preparacion: [
      { titulo: 'Paso 1', descripcion: 'En la olla, dorá la cebolla de verdeo y los champiñones fileteados hasta que suelten su agua y se doren un poco.' },
      { titulo: 'Paso 2', descripcion: 'Agregá el repollo en tiritas y mezclá bien.' },
      { titulo: 'Paso 3', descripcion: 'Volcá el caldo de hueso caliente.' },
      { titulo: 'Paso 4', descripcion: 'Cociná por 20 minutos. El repollo queda como si fueran fideos y los champiñones dan una textura firme perfecta para masticar y llenarte rápido.' },
    ],
  },
  {
    id: 18,
    numero: '18',
    nombre: 'Crema de Coliflor y Ajo Asado',
    subtitulo: 'Efecto falsa papa',
    categoria_sopa: 'Saciantes',
    caldo_base_sugerido_id: 1,
    porciones: '4',
    porcionesBase: 4,
    ingredientes: [
      { categoria: 'Verdulería', nombre: 'Coliflor grande separada en flores', cantidad_base: 1, unidad: 'planta' },
      { categoria: 'Verdulería', nombre: 'Ajo asado', cantidad_base: 1, unidad: 'cabeza' },
      { categoria: 'Verdulería', nombre: 'Cebolla blanca', cantidad_base: 1, unidad: 'un' },
      { categoria: 'Preparaciones base', nombre: 'Caldo Base de Vegetales', cantidad_base: 1, unidad: 'litro' },
    ],
    pasos_preparacion: [
      { titulo: 'Paso 1', descripcion: 'Rehogá la cebolla blanca picada hasta que esté transparente.' },
      { titulo: 'Paso 2', descripcion: 'Sumá las flores de coliflor, el puré de la cabeza de ajo asada y el caldo.' },
      { titulo: 'Paso 3', descripcion: 'Herví por 15 a 20 minutos hasta que el coliflor se deshaga al pincharlo.' },
      { titulo: 'Paso 4', descripcion: 'Procesá muy bien con minipimer hasta lograr la textura exacta de un puré liviano y cremoso.' },
    ],
  },
  {
    id: 19,
    numero: '19',
    nombre: 'Sopa de Acelga, Puerro y Zapallito',
    subtitulo: 'Verde denso',
    categoria_sopa: 'Saciantes',
    caldo_base_sugerido_id: 4,
    porciones: '4',
    porcionesBase: 4,
    ingredientes: [
      { categoria: 'Verdulería', nombre: 'Acelga grande lavada sin pencas duras', cantidad_base: 1, unidad: 'atado' },
      { categoria: 'Verdulería', nombre: 'Puerros grandes', cantidad_base: 2, unidad: 'un' },
      { categoria: 'Verdulería', nombre: 'Zapallitos verdes en cubos', cantidad_base: 3, unidad: 'un' },
      { categoria: 'Preparaciones base', nombre: 'Caldo Base Funcional Deshinchante', cantidad_base: 1, unidad: 'litro' },
    ],
    pasos_preparacion: [
      { titulo: 'Paso 1', descripcion: 'Dorá apenas los puerros picados en la olla.' },
      { titulo: 'Paso 2', descripcion: 'Agregá los zapallitos y cociná por 10 minutos.' },
      { titulo: 'Paso 3', descripcion: 'Sumá el caldo y dejá que rompa hervor.' },
      { titulo: 'Paso 4', descripcion: 'Apagá el fuego, meté todas las hojas de acelga crudas (se van a achicar con el calor residual) y procesá todo hasta obtener una crema verde espesa.' },
    ],
  },
  {
    id: 20,
    numero: '20',
    nombre: 'Caldo Espeso de Tomate y Berenjena Asada',
    subtitulo: 'Sabor profundo',
    categoria_sopa: 'Saciantes',
    caldo_base_sugerido_id: 1,
    porciones: '3',
    porcionesBase: 3,
    ingredientes: [
      { categoria: 'Verdulería', nombre: 'Berenjenas medianas', cantidad_base: 2, unidad: 'un' },
      { categoria: 'Verdulería', nombre: 'Tomates perita maduros', cantidad_base: 3, unidad: 'un' },
      { categoria: 'Verdulería', nombre: 'Ajo', cantidad_base: 1, unidad: 'diente' },
      { categoria: 'Preparaciones base', nombre: 'Caldo Base de Vegetales', cantidad_base: 1, unidad: 'litro' },
    ],
    pasos_preparacion: [
      { titulo: 'Paso 1', descripcion: 'Cortá las berenjenas a la mitad, hacele unos cortes a la pulpa y hornealas hasta que estén blandísimas. Raspá toda la pulpa con una cuchara.' },
      { titulo: 'Paso 2', descripcion: 'En la olla, poné los tomates picados, el ajo y la pulpa de berenjena.' },
      { titulo: 'Paso 3', descripcion: 'Volcá el caldo y cociná por 15 minutos para integrar los sabores.' },
      { titulo: 'Paso 4', descripcion: 'Procesá ligeramente para que quede espeso pero con algo de textura.' },
    ],
  },
  {
    id: 21,
    numero: '21',
    nombre: 'Crema de Espinaca y Zapallo Anco',
    subtitulo: 'Dulzor saciante',
    categoria_sopa: 'Saciantes',
    caldo_base_sugerido_id: 1,
    porciones: '4',
    porcionesBase: 4,
    ingredientes: [
      { categoria: 'Verdulería', nombre: 'Zapallo anco pelado y en cubos', cantidad_base: 0.5, unidad: 'un' },
      { categoria: 'Verdulería', nombre: 'Espinaca fresca lavada', cantidad_base: 1, unidad: 'atado' },
      { categoria: 'Verdulería', nombre: 'Cebolla blanca', cantidad_base: 1, unidad: 'un' },
      { categoria: 'Preparaciones base', nombre: 'Caldo Base de Vegetales', cantidad_base: 1, unidad: 'litro' },
    ],
    pasos_preparacion: [
      { titulo: 'Paso 1', descripcion: 'Rehogá la cebolla e incorporá el zapallo en cubos.' },
      { titulo: 'Paso 2', descripcion: 'Agregá el caldo y herví hasta que el zapallo esté súper tierno.' },
      { titulo: 'Paso 3', descripcion: 'Apagá el fuego, sumá las hojas de espinaca enteras y procesá de inmediato para lograr una crema de color verde intenso y textura densa.' },
    ],
  },
  {
    id: 22,
    numero: '22',
    nombre: 'Sopa en Hebras de Repollo Morado y Cebolla',
    subtitulo: 'Volumen visual',
    categoria_sopa: 'Saciantes',
    caldo_base_sugerido_id: 2,
    porciones: '3',
    porcionesBase: 3,
    ingredientes: [
      { categoria: 'Verdulería', nombre: 'Repollo morado en tiras muy finas', cantidad_base: 0.5, unidad: 'un' },
      { categoria: 'Verdulería', nombre: 'Cebollas moradas grandes en pluma', cantidad_base: 2, unidad: 'un' },
      { categoria: 'Almacén', nombre: 'Vinagre de manzana', cantidad_base: 1, unidad: 'chorrito' },
      { categoria: 'Preparaciones base', nombre: 'Caldo Base de Huesos', cantidad_base: 1, unidad: 'litro' },
    ],
    pasos_preparacion: [
      { titulo: 'Paso 1', descripcion: 'Rehogá la cebolla morada. Cuando esté blanda, agregá el repollo morado y el chorrito de vinagre.' },
      { titulo: 'Paso 2', descripcion: 'Volcá el caldo de hueso caliente.' },
      { titulo: 'Paso 3', descripcion: 'Cociná tapado por 25 minutos. Serví sin procesar, disfrutando la textura crujiente de los vegetales.' },
    ],
  },
  {
    id: 23,
    numero: '23',
    nombre: 'Crema de Brócoli y Zanahoria',
    subtitulo: 'Alta densidad',
    categoria_sopa: 'Saciantes',
    caldo_base_sugerido_id: 1,
    porciones: '4',
    porcionesBase: 4,
    ingredientes: [
      { categoria: 'Verdulería', nombre: 'Brócoli', cantidad_base: 1, unidad: 'planta' },
      { categoria: 'Verdulería', nombre: 'Zanahorias grandes cortadas finitas', cantidad_base: 3, unidad: 'un' },
      { categoria: 'Verdulería', nombre: 'Cebolla de verdeo', cantidad_base: 1, unidad: 'un' },
      { categoria: 'Preparaciones base', nombre: 'Caldo Base de Vegetales', cantidad_base: 1, unidad: 'litro' },
    ],
    pasos_preparacion: [
      { titulo: 'Paso 1', descripcion: 'Dorá el verdeo picado, sumá la zanahoria y el brócoli en flores.' },
      { titulo: 'Paso 2', descripcion: 'Agregá el caldo y cociná por 20 minutos a fuego medio.' },
      { titulo: 'Paso 3', descripcion: 'Procesá todo. Si la querés aún más espesa, podés reservar algunas florcitas de brócoli enteras para poner arriba del plato servido.' },
    ],
  },
  {
    id: 24,
    numero: '24',
    nombre: 'Caldo de Hueso con Fideos de Zapallito',
    subtitulo: 'Efecto pasta',
    categoria_sopa: 'Saciantes',
    caldo_base_sugerido_id: 2,
    porciones: '2',
    porcionesBase: 2,
    ingredientes: [
      { categoria: 'Verdulería', nombre: 'Zapallitos verdes firmes', cantidad_base: 3, unidad: 'un' },
      { categoria: 'Verdulería', nombre: 'Cebolla chica', cantidad_base: 1, unidad: 'un' },
      { categoria: 'Preparaciones base', nombre: 'Caldo Base de Huesos', cantidad_base: 1, unidad: 'litro' },
    ],
    pasos_preparacion: [
      { titulo: 'Paso 1', descripcion: 'Cortá los zapallitos en tiritas largas y finas simulando fideos (podés usar un pelapapas o un espiralizador si tenés).' },
      { titulo: 'Paso 2', descripcion: 'Calentá el caldo de hueso en la olla junto con la cebolla picadita.' },
      { titulo: 'Paso 3', descripcion: 'Cuando esté hirviendo, apagá el fuego y tirá los "fideos" de zapallito adentro. Tapá la olla por 3 minutos. Los zapallitos se ablandan pero no se desarman, quedando con la textura de la pasta.' },
    ],
  },
  {
    id: 25,
    numero: '25',
    nombre: 'Sopa Crema de Puerro y Coliflor',
    subtitulo: 'Textura aterciopelada',
    categoria_sopa: 'Saciantes',
    caldo_base_sugerido_id: 1,
    porciones: '4',
    porcionesBase: 4,
    ingredientes: [
      { categoria: 'Verdulería', nombre: 'Puerros grandes en rueditas', cantidad_base: 4, unidad: 'un' },
      { categoria: 'Verdulería', nombre: 'Coliflor en arbolitos', cantidad_base: 0.5, unidad: 'planta' },
      { categoria: 'Preparaciones base', nombre: 'Caldo Base de Vegetales', cantidad_base: 1, unidad: 'litro' },
    ],
    pasos_preparacion: [
      { titulo: 'Paso 1', descripcion: 'Rehogá el puerro muy despacio para que no se queme y suelte su dulzor.' },
      { titulo: 'Paso 2', descripcion: 'Sumá el coliflor y volcá el caldo.' },
      { titulo: 'Paso 3', descripcion: 'Cociná 20 minutos hasta que ambos vegetales estén tiernos.' },
      { titulo: 'Paso 4', descripcion: 'Procesá con fuerza hasta lograr una crema blanca y sedosa.' },
    ],
  },
  {
    id: 26,
    numero: '26',
    nombre: 'Sopa Rústica de Tomate y Morrón Asado',
    subtitulo: 'Masticación extra',
    categoria_sopa: 'Saciantes',
    caldo_base_sugerido_id: 1,
    porciones: '3',
    porcionesBase: 3,
    ingredientes: [
      { categoria: 'Verdulería', nombre: 'Morrones rojos grandes asados y pelados', cantidad_base: 2, unidad: 'un' },
      { categoria: 'Verdulería', nombre: 'Tomates perita en cubos grandes', cantidad_base: 4, unidad: 'un' },
      { categoria: 'Verdulería', nombre: 'Ajo picado grueso', cantidad_base: 1, unidad: 'diente' },
      { categoria: 'Preparaciones base', nombre: 'Caldo Base de Vegetales', cantidad_base: 1, unidad: 'litro' },
    ],
    pasos_preparacion: [
      { titulo: 'Paso 1', descripcion: 'Cortá los morrones asados en cuadrados grandes.' },
      { titulo: 'Paso 2', descripcion: 'En la olla, poné el ajo, el tomate y el morrón. Volcá el caldo.' },
      { titulo: 'Paso 3', descripcion: 'Herví por solo 10 minutos para que el tomate no se deshaga del todo. Serví así, en trozos, para obligarte a comer despacio.' },
    ],
  },
  {
    id: 27,
    numero: '27',
    nombre: 'Crema Densa de Cebolla y Zapallo Cabutia',
    subtitulo: 'Confort total',
    categoria_sopa: 'Saciantes',
    caldo_base_sugerido_id: 1,
    porciones: '4',
    porcionesBase: 4,
    ingredientes: [
      { categoria: 'Verdulería', nombre: 'Zapallo cabutia grande', cantidad_base: 0.5, unidad: 'un' },
      { categoria: 'Verdulería', nombre: 'Cebollas blancas', cantidad_base: 2, unidad: 'un' },
      { categoria: 'Preparaciones base', nombre: 'Caldo Base de Vegetales', cantidad_base: 1, unidad: 'litro' },
    ],
    pasos_preparacion: [
      { titulo: 'Paso 1', descripcion: 'Rehogá la cebolla en trozos grandes.' },
      { titulo: 'Paso 2', descripcion: 'Agregá el zapallo cabutia en cubos. Si dejás la cáscara verde, la sopa te va a quedar más oscura pero con el doble de fibra.' },
      { titulo: 'Paso 3', descripcion: 'Cubrí con el caldo y cociná por 30 minutos (el cabutia tarda un poquito más en ablandar).' },
      { titulo: 'Paso 4', descripcion: 'Procesá todo hasta que quede una crema súper pesada visualmente, pero liviana para el cuerpo.' },
    ],
  },
  {
    id: 28,
    numero: '28',
    nombre: 'Caldo Saciante de Espinaca y Champiñones',
    subtitulo: 'Umami natural',
    categoria_sopa: 'Saciantes',
    caldo_base_sugerido_id: 2,
    notaCaldoBase: 'La receta permite caldo base de hueso o vegetales; se recomienda el primero mencionado.',
    porciones: '2',
    porcionesBase: 2,
    ingredientes: [
      { categoria: 'Verdulería', nombre: 'Champiñones frescos', cantidad_base: 200, unidad: 'g' },
      { categoria: 'Verdulería', nombre: 'Espinaca fresca', cantidad_base: 1, unidad: 'atado' },
      { categoria: 'Verdulería', nombre: 'Ajo', cantidad_base: 1, unidad: 'diente' },
      { categoria: 'Preparaciones base', nombre: 'Caldo Base de Huesos', cantidad_base: 1, unidad: 'litro' },
    ],
    pasos_preparacion: [
      { titulo: 'Paso 1', descripcion: 'Dorá los champiñones enteros o cortados al medio junto con el ajo picado.' },
      { titulo: 'Paso 2', descripcion: 'Volcá el caldo y calentá hasta que hierva.' },
      { titulo: 'Paso 3', descripcion: 'Apagá el fuego, sumá las hojas de espinaca frescas y serví de inmediato. Vas a tener que masticar cada cucharada.' },
    ],
  },
  {
    id: 29,
    numero: '29',
    nombre: 'Crema de Zanahoria y Apio',
    subtitulo: 'Fibra prolongada',
    categoria_sopa: 'Saciantes',
    caldo_base_sugerido_id: 4,
    porciones: '3',
    porcionesBase: 3,
    ingredientes: [
      { categoria: 'Verdulería', nombre: 'Zanahorias grandes en ruedas', cantidad_base: 4, unidad: 'un' },
      { categoria: 'Verdulería', nombre: 'Apio bien picado', cantidad_base: 4, unidad: 'ramas' },
      { categoria: 'Verdulería', nombre: 'Cebolla de verdeo', cantidad_base: 1, unidad: 'un' },
      { categoria: 'Preparaciones base', nombre: 'Caldo Base Funcional Deshinchante', cantidad_base: 1, unidad: 'litro' },
    ],
    pasos_preparacion: [
      { titulo: 'Paso 1', descripcion: 'Rehogá el verdeo, el apio y las zanahorias.' },
      { titulo: 'Paso 2', descripcion: 'Volcá el caldo y cociná por 25 minutos.' },
      { titulo: 'Paso 3', descripcion: 'Procesá todo muy bien. La fibra del apio hace que la sopa quede muy consistente y te llene al instante.' },
    ],
  },
  {
    id: 30,
    numero: '30',
    nombre: 'Sopa Abundante de Zapallitos y Repollo Blanco',
    subtitulo: 'Llenado rápido',
    categoria_sopa: 'Saciantes',
    caldo_base_sugerido_id: 1,
    porciones: '4',
    porcionesBase: 4,
    ingredientes: [
      { categoria: 'Verdulería', nombre: 'Zapallitos verdes en cubos', cantidad_base: 4, unidad: 'un' },
      { categoria: 'Verdulería', nombre: 'Repollo blanco en tiritas', cantidad_base: 0.5, unidad: 'un' },
      { categoria: 'Verdulería', nombre: 'Cebolla blanca', cantidad_base: 1, unidad: 'un' },
      { categoria: 'Preparaciones base', nombre: 'Caldo Base de Vegetales', cantidad_base: 1, unidad: 'litro' },
    ],
    pasos_preparacion: [
      { titulo: 'Paso 1', descripcion: 'Rehogá la cebolla, sumá los zapallitos y el repollo.' },
      { titulo: 'Paso 2', descripcion: 'Revolvé bien hasta que el repollo pierda volumen.' },
      { titulo: 'Paso 3', descripcion: 'Cubrí con el caldo y cociná 20 minutos.' },
      { titulo: 'Paso 4', descripcion: 'Comela así, con todos los trozos enteros, o procesala. Ambas formas son un tanque de saciedad absoluto.' },
    ],
  },
  {
    id: 31,
    numero: '31',
    nombre: 'Crema Verde Deshinchante',
    subtitulo: 'Diurética pura',
    categoria_sopa: 'Deshinchantes',
    caldo_base_sugerido_id: 4,
    porciones: '4',
    porcionesBase: 4,
    ingredientes: [
      { categoria: 'Verdulería', nombre: 'Apio lavado y picado', cantidad_base: 1, unidad: 'planta' },
      { categoria: 'Verdulería', nombre: 'Zapallitos verdes en cubos', cantidad_base: 4, unidad: 'un' },
      { categoria: 'Verdulería', nombre: 'Cebolla blanca', cantidad_base: 1, unidad: 'un' },
      { categoria: 'Preparaciones base', nombre: 'Caldo Base Funcional Deshinchante', cantidad_base: 1, unidad: 'litro' },
    ],
    pasos_preparacion: [
      { titulo: 'Paso 1', descripcion: 'Rehogá la cebolla y el apio picado en una olla hasta que empiecen a ablandar.' },
      { titulo: 'Paso 2', descripcion: 'Sumá los zapallitos en cubos y mezclá bien.' },
      { titulo: 'Paso 3', descripcion: 'Volcá el caldo caliente y cociná por 20 minutos.' },
      { titulo: 'Paso 4', descripcion: 'Procesá todo con minipimer. Si te quedan algunos hilitos del apio, podés pasarla por un colador grueso, aunque esa fibra es excelente para la digestión.' },
    ],
  },
  {
    id: 32,
    numero: '32',
    nombre: 'Caldo Claro de Puerro y Perejil',
    subtitulo: 'Limpieza suave',
    categoria_sopa: 'Deshinchantes',
    caldo_base_sugerido_id: 1,
    porciones: '2',
    porcionesBase: 2,
    ingredientes: [
      { categoria: 'Verdulería', nombre: 'Puerros grandes en rueditas muy finas', cantidad_base: 3, unidad: 'un' },
      { categoria: 'Verdulería', nombre: 'Perejil fresco', cantidad_base: 1, unidad: 'puñado grande' },
      { categoria: 'Preparaciones base', nombre: 'Caldo Base de Vegetales', cantidad_base: 1, unidad: 'litro' },
    ],
    pasos_preparacion: [
      { titulo: 'Paso 1', descripcion: 'Dorá el puerro lentamente con un hilito de agua para que no tome color oscuro, solo tiene que quedar transparente y dulce.' },
      { titulo: 'Paso 2', descripcion: 'Volcá el caldo de vegetales y dejá hervir por 15 minutos.' },
      { titulo: 'Paso 3', descripcion: 'Apagá el fuego, agregá el perejil fresco picado bien chiquito, tapá la olla y dejá infusionar 5 minutos antes de tomarlo. Se toma sin procesar.' },
    ],
  },
  {
    id: 33,
    numero: '33',
    nombre: 'Sopa Liviana de Tomate y Albahaca',
    subtitulo: 'Puro líquido',
    categoria_sopa: 'Deshinchantes',
    caldo_base_sugerido_id: 1,
    porciones: '3',
    porcionesBase: 3,
    ingredientes: [
      { categoria: 'Verdulería', nombre: 'Tomates perita maduros pelados y sin semillas', cantidad_base: 5, unidad: 'un' },
      { categoria: 'Verdulería', nombre: 'Ajo', cantidad_base: 1, unidad: 'diente' },
      { categoria: 'Verdulería', nombre: 'Albahaca fresca', cantidad_base: 1, unidad: 'puñado' },
      { categoria: 'Preparaciones base', nombre: 'Caldo Base de Vegetales', cantidad_base: 1, unidad: 'litro' },
    ],
    pasos_preparacion: [
      { titulo: 'Paso 1', descripcion: 'Poné los tomates limpios y el ajo en la olla junto con el caldo.' },
      { titulo: 'Paso 2', descripcion: 'Herví a fuego medio por 15 minutos.' },
      { titulo: 'Paso 3', descripcion: 'Procesá todo hasta que quede un caldo rojo y parejo.' },
      { titulo: 'Paso 4', descripcion: 'Serví caliente con las hojas de albahaca fresca rotas con la mano por encima.' },
    ],
  },
  {
    id: 34,
    numero: '34',
    nombre: 'Crema Fluida de Zanahoria y Caldo Funcional',
    subtitulo: 'Dulzor sin pesadez',
    categoria_sopa: 'Deshinchantes',
    caldo_base_sugerido_id: 4,
    porciones: '3',
    porcionesBase: 3,
    ingredientes: [
      { categoria: 'Verdulería', nombre: 'Zanahorias medianas en rodajas finas', cantidad_base: 4, unidad: 'un' },
      { categoria: 'Verdulería', nombre: 'Cebolla de verdeo', cantidad_base: 1, unidad: 'un' },
      { categoria: 'Preparaciones base', nombre: 'Caldo Base Funcional Deshinchante', cantidad_base: 1, unidad: 'litro' },
    ],
    pasos_preparacion: [
      { titulo: 'Paso 1', descripcion: 'Rehogá la parte blanca de la cebolla de verdeo en la olla.' },
      { titulo: 'Paso 2', descripcion: 'Agregá las zanahorias y el caldo funcional.' },
      { titulo: 'Paso 3', descripcion: 'Cociná 20 minutos hasta que la zanahoria esté súper tierna.' },
      { titulo: 'Paso 4', descripcion: 'Procesá muy bien. Al tener menos masa vegetal, queda como una crema fluida, ideal para tomar en taza.' },
    ],
  },
  {
    id: 35,
    numero: '35',
    nombre: 'Caldo de Pescado con Tiras de Acelga',
    subtitulo: 'Proteína extra liviana',
    categoria_sopa: 'Deshinchantes',
    caldo_base_sugerido_id: 3,
    porciones: '2',
    porcionesBase: 2,
    ingredientes: [
      { categoria: 'Verdulería', nombre: 'Acelga lavada (solo hojas verdes)', cantidad_base: 1, unidad: 'atado' },
      { categoria: 'Verdulería', nombre: 'Ajo picado', cantidad_base: 1, unidad: 'diente' },
      { categoria: 'Preparaciones base', nombre: 'Caldo Base de Pescado', cantidad_base: 1, unidad: 'litro' },
    ],
    pasos_preparacion: [
      { titulo: 'Paso 1', descripcion: 'Calentá el caldo de pescado en la olla.' },
      { titulo: 'Paso 2', descripcion: 'Cortá las hojas de acelga en tiritas bien finas (como si fueran fideos).' },
      { titulo: 'Paso 3', descripcion: 'Cuando el caldo rompa el hervor, agregá el ajo picado y las tiritas de acelga.' },
      { titulo: 'Paso 4', descripcion: 'Apagá el fuego al minuto. La acelga se cocina con el calor residual y el caldo queda súper limpio.' },
    ],
  },
  {
    id: 36,
    numero: '36',
    nombre: 'Sopa de Cebolla Blanca y Tomillo',
    subtitulo: 'Digestión rápida',
    categoria_sopa: 'Deshinchantes',
    caldo_base_sugerido_id: 1,
    porciones: '3',
    porcionesBase: 3,
    ingredientes: [
      { categoria: 'Verdulería', nombre: 'Cebollas blancas grandes en pluma', cantidad_base: 4, unidad: 'un' },
      { categoria: 'Almacén', nombre: 'Tomillo seco', cantidad_base: 1, unidad: 'cdita' },
      { categoria: 'Preparaciones base', nombre: 'Caldo Base de Vegetales', cantidad_base: 1, unidad: 'litro' },
    ],
    pasos_preparacion: [
      { titulo: 'Paso 1', descripcion: 'Poné la cebolla en la olla y cocinala a fuego mínimo por unos 15 minutos, revolviendo para que no se queme, hasta que reduzca a la mitad y esté muy dulce.' },
      { titulo: 'Paso 2', descripcion: 'Agregá el tomillo y el caldo.' },
      { titulo: 'Paso 3', descripcion: 'Herví por 15 minutos más. Podés tomarla así (sopa de cebolla clásica) o procesarla si preferís una textura lisa.' },
    ],
  },
  {
    id: 37,
    numero: '37',
    nombre: 'Crema de Espinaca y Puerro',
    subtitulo: 'Hierro sin carga',
    categoria_sopa: 'Deshinchantes',
    caldo_base_sugerido_id: 1,
    porciones: '4',
    porcionesBase: 4,
    ingredientes: [
      { categoria: 'Verdulería', nombre: 'Espinaca fresca (solo hojas)', cantidad_base: 2, unidad: 'atados' },
      { categoria: 'Verdulería', nombre: 'Puerros grandes picados', cantidad_base: 2, unidad: 'un' },
      { categoria: 'Preparaciones base', nombre: 'Caldo Base de Vegetales', cantidad_base: 1, unidad: 'litro' },
    ],
    pasos_preparacion: [
      { titulo: 'Paso 1', descripcion: 'Rehogá el puerro lentamente.' },
      { titulo: 'Paso 2', descripcion: 'Volcá el caldo y llevá a hervor por 10 minutos.' },
      { titulo: 'Paso 3', descripcion: 'Apagá el fuego y meté todas las hojas de espinaca crudas en el líquido caliente.' },
      { titulo: 'Paso 4', descripcion: 'Procesá inmediatamente. Hacerlo así conserva el color verde intenso y evita que la espinaca caiga pesada.' },
    ],
  },
  {
    id: 38,
    numero: '38',
    nombre: 'Caldo de Ajo Asado y Cúrcuma',
    subtitulo: 'Desinflamación profunda',
    categoria_sopa: 'Deshinchantes',
    caldo_base_sugerido_id: 1,
    porciones: '2',
    porcionesBase: 2,
    ingredientes: [
      { categoria: 'Verdulería', nombre: 'Ajo asado al horno', cantidad_base: 1, unidad: 'cabeza' },
      { categoria: 'Almacén', nombre: 'Cúrcuma en polvo', cantidad_base: 1, unidad: 'cdita generosa' },
      { categoria: 'Almacén', nombre: 'Pimienta negra', cantidad_base: 1, unidad: 'pizca' },
      { categoria: 'Preparaciones base', nombre: 'Caldo Base de Vegetales', cantidad_base: 1, unidad: 'litro' },
    ],
    pasos_preparacion: [
      { titulo: 'Paso 1', descripcion: 'En una olla, mezclá el puré de ajo asado con la cúrcuma y la pimienta.' },
      { titulo: 'Paso 2', descripcion: 'Agregá un chorrito de caldo y formá una pasta revolviendo con cuchara.' },
      { titulo: 'Paso 3', descripcion: 'Volcá el resto del caldo, revolvé bien para integrar todo y calentá a fuego medio hasta que hierva suavemente por 5 minutos.' },
    ],
  },
  {
    id: 39,
    numero: '39',
    nombre: 'Sopa Rápida de Verdeo y Zanahoria Rallada',
    subtitulo: 'Fibra ligera',
    categoria_sopa: 'Deshinchantes',
    caldo_base_sugerido_id: 4,
    porciones: '3',
    porcionesBase: 3,
    ingredientes: [
      { categoria: 'Verdulería', nombre: 'Cebolla de verdeo picada fina', cantidad_base: 4, unidad: 'ramas' },
      { categoria: 'Verdulería', nombre: 'Zanahorias medianas ralladas finitas', cantidad_base: 3, unidad: 'un' },
      { categoria: 'Preparaciones base', nombre: 'Caldo Base Funcional Deshinchante', cantidad_base: 1, unidad: 'litro' },
    ],
    pasos_preparacion: [
      { titulo: 'Paso 1', descripcion: 'En la olla, dorá apenas el verdeo.' },
      { titulo: 'Paso 2', descripcion: 'Sumá la zanahoria rallada, revolvé un minuto.' },
      { titulo: 'Paso 3', descripcion: 'Cubrí con el caldo caliente y cociná por 10 minutos.' },
      { titulo: 'Paso 4', descripcion: 'Tomala así, rústica. Es súper liviana pero te obliga a masticar un poco.' },
    ],
  },
  {
    id: 40,
    numero: '40',
    nombre: 'Crema de Zapallo Anco Extra Líquida',
    subtitulo: 'Para no cargar el estómago',
    categoria_sopa: 'Deshinchantes',
    caldo_base_sugerido_id: 1,
    porciones: '4',
    porcionesBase: 4,
    ingredientes: [
      { categoria: 'Verdulería', nombre: 'Zapallo anco pelado en cubitos chiquitos', cantidad_base: 0.25, unidad: 'un' },
      { categoria: 'Verdulería', nombre: 'Cebolla chica', cantidad_base: 1, unidad: 'un' },
      { categoria: 'Preparaciones base', nombre: 'Caldo Base de Vegetales', cantidad_base: 1.5, unidad: 'litros' },
    ],
    pasos_preparacion: [
      { titulo: 'Paso 1', descripcion: 'Rehogá la cebolla.' },
      { titulo: 'Paso 2', descripcion: 'Agregá los cubitos de zapallo y volcá todo el caldo.' },
      { titulo: 'Paso 3', descripcion: 'Cociná 20 minutos hasta que el zapallo se desarme solo.' },
      { titulo: 'Paso 4', descripcion: 'Procesá bien. Te va a quedar una sopa con sabor a calabaza, pero con la textura de un caldo espeso.' },
    ],
  },
  {
    id: 41,
    numero: '41',
    nombre: 'Caldo Depurativo de Apio y Jengibre',
    subtitulo: 'Efecto barrido',
    categoria_sopa: 'Deshinchantes',
    caldo_base_sugerido_id: 1,
    porciones: '3',
    porcionesBase: 3,
    ingredientes: [
      { categoria: 'Verdulería', nombre: 'Apio picado', cantidad_base: 1, unidad: 'planta' },
      { categoria: 'Verdulería', nombre: 'Jengibre fresco', cantidad_base: 1, unidad: 'rodaja grande' },
      { categoria: 'Preparaciones base', nombre: 'Caldo Base de Vegetales', cantidad_base: 1, unidad: 'litro' },
    ],
    pasos_preparacion: [
      { titulo: 'Paso 1', descripcion: 'Poné el apio y el jengibre entero en la olla.' },
      { titulo: 'Paso 2', descripcion: 'Cubrí con el caldo y herví a fuego medio por 25 minutos.' },
      { titulo: 'Paso 3', descripcion: 'Colá la preparación (descartá los trozos de apio y jengibre). Tomá solo el caldo resultante, que va a estar lleno de sabor y propiedades diuréticas.' },
    ],
  },
  {
    id: 42,
    numero: '42',
    nombre: 'Sopa de Repollo Blanco y Caldo Funcional',
    subtitulo: 'Súper diurética',
    categoria_sopa: 'Deshinchantes',
    caldo_base_sugerido_id: 4,
    porciones: '3',
    porcionesBase: 3,
    ingredientes: [
      { categoria: 'Verdulería', nombre: 'Repollo blanco en tiras extremadamente finas', cantidad_base: 0.25, unidad: 'un' },
      { categoria: 'Verdulería', nombre: 'Cebolla blanca', cantidad_base: 1, unidad: 'un' },
      { categoria: 'Preparaciones base', nombre: 'Caldo Base Funcional Deshinchante', cantidad_base: 1, unidad: 'litro' },
    ],
    pasos_preparacion: [
      { titulo: 'Paso 1', descripcion: 'Rehogá la cebolla hasta que transparente.' },
      { titulo: 'Paso 2', descripcion: 'Sumá las tiras de repollo y revolvé un minuto.' },
      { titulo: 'Paso 3', descripcion: 'Agregá el caldo caliente y cociná tapado a fuego mínimo por 20 minutos. El repollo debe quedar translúcido. Serví sin procesar.' },
    ],
  },
  {
    id: 43,
    numero: '43',
    nombre: 'Crema de Zapallitos al Orégano',
    subtitulo: 'Sabor a pizza, cuerpo liviano',
    categoria_sopa: 'Deshinchantes',
    caldo_base_sugerido_id: 1,
    porciones: '3',
    porcionesBase: 3,
    ingredientes: [
      { categoria: 'Verdulería', nombre: 'Zapallitos verdes en cubos grandes', cantidad_base: 5, unidad: 'un' },
      { categoria: 'Verdulería', nombre: 'Cebolla', cantidad_base: 1, unidad: 'un' },
      { categoria: 'Almacén', nombre: 'Orégano seco', cantidad_base: 1, unidad: 'cda sopera' },
      { categoria: 'Preparaciones base', nombre: 'Caldo Base de Vegetales', cantidad_base: 1, unidad: 'litro' },
    ],
    pasos_preparacion: [
      { titulo: 'Paso 1', descripcion: 'Rehogá la cebolla y los zapallitos en la olla.' },
      { titulo: 'Paso 2', descripcion: 'Espolvoreá el orégano y mezclá bien para que se humedezca y suelte el aroma.' },
      { titulo: 'Paso 3', descripcion: 'Volcá el caldo y cociná 15 minutos.' },
      { titulo: 'Paso 4', descripcion: 'Procesá hasta que quede una crema suave con pintitas verdes de orégano.' },
    ],
  },
  {
    id: 44,
    numero: '44',
    nombre: 'Caldo Limpio con Flores de Brócoli',
    subtitulo: 'Textura sin pesadez',
    categoria_sopa: 'Deshinchantes',
    caldo_base_sugerido_id: 2,
    porciones: '2',
    porcionesBase: 2,
    ingredientes: [
      { categoria: 'Verdulería', nombre: 'Flores de brócoli muy chiquitas', cantidad_base: 1, unidad: 'taza' },
      { categoria: 'Verdulería', nombre: 'Ajo', cantidad_base: 1, unidad: 'diente' },
      { categoria: 'Preparaciones base', nombre: 'Caldo Base de Huesos', cantidad_base: 1, unidad: 'litro' },
    ],
    pasos_preparacion: [
      { titulo: 'Paso 1', descripcion: 'Calentá el caldo de hueso en la olla junto con el diente de ajo entero.' },
      { titulo: 'Paso 2', descripcion: 'Cuando hierva a borbotones, tirá las mini flores de brócoli.' },
      { titulo: 'Paso 3', descripcion: 'Cociná destapado exactamente 5 minutos y apagá. Te queda un caldo sustancioso con florcitas crujientes y fáciles de digerir.' },
    ],
  },
  {
    id: 45,
    numero: '45',
    nombre: 'Sopa de Tomate y Apio Picado',
    subtitulo: 'Fresca y caliente a la vez',
    categoria_sopa: 'Deshinchantes',
    caldo_base_sugerido_id: 4,
    porciones: '3',
    porcionesBase: 3,
    ingredientes: [
      { categoria: 'Verdulería', nombre: 'Tomates perita maduros pelados y picados', cantidad_base: 3, unidad: 'un' },
      { categoria: 'Verdulería', nombre: 'Apio picado bien chiquito', cantidad_base: 3, unidad: 'ramas' },
      { categoria: 'Preparaciones base', nombre: 'Caldo Base Funcional Deshinchante', cantidad_base: 1, unidad: 'litro' },
    ],
    pasos_preparacion: [
      { titulo: 'Paso 1', descripcion: 'En la olla, poné el tomate picado y el apio.' },
      { titulo: 'Paso 2', descripcion: 'Agregá el caldo funcional.' },
      { titulo: 'Paso 3', descripcion: 'Herví a fuego suave por 20 minutos.' },
      { titulo: 'Paso 4', descripcion: 'Podés tomarla así (tipo sopa minestrone pero sin pasta) o darle apenas un toque con la minipimer para que quede con algo de textura.' },
    ],
  },
  {
    id: 46,
    numero: '46',
    nombre: 'Crema de Zapallo y Choclo',
    subtitulo: 'Sabor a humita liviana',
    categoria_sopa: 'Cremosas Livianas',
    caldo_base_sugerido_id: 1,
    porciones: '4',
    porcionesBase: 4,
    ingredientes: [
      { categoria: 'Verdulería', nombre: 'Zapallo anco pelado y en cubos', cantidad_base: 0.5, unidad: 'un' },
      { categoria: 'Verdulería', nombre: 'Granos de choclo amarillo', cantidad_base: 1, unidad: 'taza' },
      { categoria: 'Verdulería', nombre: 'Cebolla blanca', cantidad_base: 1, unidad: 'un' },
      { categoria: 'Preparaciones base', nombre: 'Caldo Base de Vegetales', cantidad_base: 1, unidad: 'litro' },
    ],
    pasos_preparacion: [
      { titulo: 'Paso 1', descripcion: 'Rehogá la cebolla en la olla hasta que transparente.' },
      { titulo: 'Paso 2', descripcion: 'Agregá los cubos de zapallo y la mitad de los granos de choclo (reservá la otra mitad).' },
      { titulo: 'Paso 3', descripcion: 'Volcá el caldo y cociná por 20 minutos a fuego medio.' },
      { titulo: 'Paso 4', descripcion: 'Procesá todo hasta lograr una crema lisa. Al servir, agregá por encima los granos de choclo enteros que reservaste para darle textura.' },
    ],
  },
  {
    id: 47,
    numero: '47',
    nombre: 'Sopa Crema de Zanahoria y Tomillo',
    subtitulo: 'El clásico casero',
    categoria_sopa: 'Cremosas Livianas',
    caldo_base_sugerido_id: 1,
    porciones: '3',
    porcionesBase: 3,
    ingredientes: [
      { categoria: 'Verdulería', nombre: 'Zanahorias grandes en rueditas', cantidad_base: 5, unidad: 'un' },
      { categoria: 'Verdulería', nombre: 'Cebolla blanca grande', cantidad_base: 1, unidad: 'un' },
      { categoria: 'Verdulería', nombre: 'Hojas de tomillo fresco', cantidad_base: 1, unidad: 'cda' },
      { categoria: 'Preparaciones base', nombre: 'Caldo Base de Vegetales', cantidad_base: 1, unidad: 'litro' },
    ],
    pasos_preparacion: [
      { titulo: 'Paso 1', descripcion: 'En la olla, dorá la cebolla y la zanahoria a fuego muy lento para que suelten su azúcar natural.' },
      { titulo: 'Paso 2', descripcion: 'Agregá el tomillo y mezclá para que libere su aroma.' },
      { titulo: 'Paso 3', descripcion: 'Cubrí con el caldo y herví 25 minutos (la zanahoria tiene que deshacerse al pincharla).' },
      { titulo: 'Paso 4', descripcion: 'Procesá con fuerza durante un minuto extra para asegurar una crema completamente sedosa y sin grumos.' },
    ],
  },
  {
    id: 48,
    numero: '48',
    nombre: 'Crema Blanca de Coliflor y Nuez Moscada',
    subtitulo: 'Efecto salsa blanca',
    categoria_sopa: 'Cremosas Livianas',
    caldo_base_sugerido_id: 1,
    porciones: '4',
    porcionesBase: 4,
    ingredientes: [
      { categoria: 'Verdulería', nombre: 'Coliflor grande separada en flores chicas', cantidad_base: 1, unidad: 'planta' },
      { categoria: 'Verdulería', nombre: 'Puerros picados', cantidad_base: 2, unidad: 'un' },
      { categoria: 'Almacén', nombre: 'Nuez moscada rallada', cantidad_base: 0.5, unidad: 'cdita' },
      { categoria: 'Preparaciones base', nombre: 'Caldo Base de Vegetales', cantidad_base: 1, unidad: 'litro' },
    ],
    pasos_preparacion: [
      { titulo: 'Paso 1', descripcion: 'Rehogá los puerros a fuego mínimo, cuidando que no se doren para no arruinar el color blanco de la sopa.' },
      { titulo: 'Paso 2', descripcion: 'Sumá el coliflor y el caldo caliente.' },
      { titulo: 'Paso 3', descripcion: 'Cociná tapado por 20 minutos.' },
      { titulo: 'Paso 4', descripcion: 'Retirá del fuego, agregá la nuez moscada y procesá. Vas a notar cómo el coliflor emulsiona creando una crema espesísima.' },
    ],
  },
  {
    id: 49,
    numero: '49',
    nombre: 'Sopa Sedosa de Zapallo Cabutia y Puerro',
    subtitulo: 'Textura de restaurante',
    categoria_sopa: 'Cremosas Livianas',
    caldo_base_sugerido_id: 2,
    porciones: '4',
    porcionesBase: 4,
    ingredientes: [
      { categoria: 'Verdulería', nombre: 'Zapallo cabutia pelado y en cubos', cantidad_base: 0.5, unidad: 'un' },
      { categoria: 'Verdulería', nombre: 'Puerros grandes en rueditas', cantidad_base: 3, unidad: 'un' },
      { categoria: 'Preparaciones base', nombre: 'Caldo Base de Huesos', cantidad_base: 1, unidad: 'litro' },
    ],
    pasos_preparacion: [
      { titulo: 'Paso 1', descripcion: 'Dorá lentamente los puerros en la olla.' },
      { titulo: 'Paso 2', descripcion: 'Sumá los cubos de cabutia y volcá el caldo de hueso.' },
      { titulo: 'Paso 3', descripcion: 'Herví por 25 a 30 minutos a fuego suave.' },
      { titulo: 'Paso 4', descripcion: 'Procesá con minipimer. Si te queda demasiado espesa, podés aligerarla con un chorrito extra de caldo caliente.' },
    ],
  },
  {
    id: 50,
    numero: '50',
    nombre: 'Crema Suave de Arvejas y Menta',
    subtitulo: 'Fresca y espesa',
    categoria_sopa: 'Cremosas Livianas',
    caldo_base_sugerido_id: 1,
    porciones: '3',
    porcionesBase: 3,
    ingredientes: [
      { categoria: 'Verdulería', nombre: 'Arvejas', cantidad_base: 2, unidad: 'tazas' },
      { categoria: 'Verdulería', nombre: 'Cebolla de verdeo', cantidad_base: 1, unidad: 'un' },
      { categoria: 'Verdulería', nombre: 'Menta fresca', cantidad_base: 1, unidad: 'hojitas' },
      { categoria: 'Preparaciones base', nombre: 'Caldo Base de Vegetales', cantidad_base: 1, unidad: 'litro' },
    ],
    pasos_preparacion: [
      { titulo: 'Paso 1', descripcion: 'Rehogá la parte blanca y verde clara de la cebolla de verdeo.' },
      { titulo: 'Paso 2', descripcion: 'Agregá las arvejas y el caldo. Si usás congeladas, cociná solo 10 minutos para que mantengan ese color verde flúor.' },
      { titulo: 'Paso 3', descripcion: 'Apagá el fuego y agregá las hojas de menta crudas.' },
      { titulo: 'Paso 4', descripcion: 'Procesá enseguida hasta que la textura sea homogénea.' },
    ],
  },
  {
    id: 51,
    numero: '51',
    nombre: 'Sopa Crema de Champiñones al Verdeo',
    subtitulo: 'Umami reconfortante',
    categoria_sopa: 'Cremosas Livianas',
    caldo_base_sugerido_id: 2,
    porciones: '3',
    porcionesBase: 3,
    ingredientes: [
      { categoria: 'Verdulería', nombre: 'Champiñones o portobellos frescos', cantidad_base: 400, unidad: 'g' },
      { categoria: 'Verdulería', nombre: 'Cebolla de verdeo picada fina', cantidad_base: 3, unidad: 'ramas' },
      { categoria: 'Verdulería', nombre: 'Ajo', cantidad_base: 1, unidad: 'diente' },
      { categoria: 'Preparaciones base', nombre: 'Caldo Base de Huesos', cantidad_base: 1, unidad: 'litro' },
    ],
    pasos_preparacion: [
      { titulo: 'Paso 1', descripcion: 'Cortá los hongos en láminas y doralos en la olla junto con el verdeo y el ajo (reservá unas laminitas de hongo dorado para decorar el plato).' },
      { titulo: 'Paso 2', descripcion: 'Volcá el caldo de hueso caliente.' },
      { titulo: 'Paso 3', descripcion: 'Cociná 15 minutos a fuego medio.' },
      { titulo: 'Paso 4', descripcion: 'Procesá la sopa. Al servir, colocá los honguitos dorados que reservaste por encima.' },
    ],
  },
  {
    id: 52,
    numero: '52',
    nombre: 'Crema de Zapallito y Albahaca',
    subtitulo: 'Suavidad verde',
    categoria_sopa: 'Cremosas Livianas',
    caldo_base_sugerido_id: 1,
    porciones: '4',
    porcionesBase: 4,
    ingredientes: [
      { categoria: 'Verdulería', nombre: 'Zapallitos verdes en cubos', cantidad_base: 6, unidad: 'un' },
      { categoria: 'Verdulería', nombre: 'Cebolla blanca', cantidad_base: 1, unidad: 'un' },
      { categoria: 'Verdulería', nombre: 'Albahaca fresca', cantidad_base: 1, unidad: 'puñado' },
      { categoria: 'Preparaciones base', nombre: 'Caldo Base de Vegetales', cantidad_base: 1, unidad: 'litro' },
    ],
    pasos_preparacion: [
      { titulo: 'Paso 1', descripcion: 'Rehogá la cebolla hasta que esté blanda.' },
      { titulo: 'Paso 2', descripcion: 'Agregá los zapallitos y cocinalos unos 10 minutos revolviendo para que suelten su propia agua.' },
      { titulo: 'Paso 3', descripcion: 'Sumá el caldo y herví 10 minutos más.' },
      { titulo: 'Paso 4', descripcion: 'Apagá el fuego, tirá las hojas de albahaca fresca adentro y procesá todo.' },
    ],
  },
  {
    id: 53,
    numero: '53',
    nombre: 'Sopa Aterciopelada de Tomate y Zanahoria',
    subtitulo: 'Dulzor natural',
    categoria_sopa: 'Cremosas Livianas',
    caldo_base_sugerido_id: 1,
    porciones: '3',
    porcionesBase: 3,
    ingredientes: [
      { categoria: 'Verdulería', nombre: 'Tomates perita maduros cubeteados', cantidad_base: 4, unidad: 'un' },
      { categoria: 'Verdulería', nombre: 'Zanahorias grandes ralladas', cantidad_base: 2, unidad: 'un' },
      { categoria: 'Verdulería', nombre: 'Cebolla blanca', cantidad_base: 1, unidad: 'un' },
      { categoria: 'Preparaciones base', nombre: 'Caldo Base de Vegetales', cantidad_base: 1, unidad: 'litro' },
    ],
    pasos_preparacion: [
      { titulo: 'Paso 1', descripcion: 'Rehogá la cebolla.' },
      { titulo: 'Paso 2', descripcion: 'Agregá la zanahoria rallada y el tomate. Cociná por 5 minutos para que el tomate empiece a deshacerse.' },
      { titulo: 'Paso 3', descripcion: 'Volcá el caldo y cociná 20 minutos a fuego bajo.' },
      { titulo: 'Paso 4', descripcion: 'Procesá todo por un buen rato. La zanahoria le va a dar ese cuerpo espeso y sedoso que el tomate solo no logra.' },
    ],
  },
  {
    id: 54,
    numero: '54',
    nombre: 'Crema de Brócoli y Coliflor',
    subtitulo: 'Doble textura',
    categoria_sopa: 'Cremosas Livianas',
    caldo_base_sugerido_id: 1,
    porciones: '4',
    porcionesBase: 4,
    ingredientes: [
      { categoria: 'Verdulería', nombre: 'Brócoli en arbolitos', cantidad_base: 0.5, unidad: 'planta' },
      { categoria: 'Verdulería', nombre: 'Coliflor en arbolitos', cantidad_base: 0.5, unidad: 'planta' },
      { categoria: 'Verdulería', nombre: 'Puerro picado', cantidad_base: 1, unidad: 'un' },
      { categoria: 'Preparaciones base', nombre: 'Caldo Base de Vegetales', cantidad_base: 1, unidad: 'litro' },
    ],
    pasos_preparacion: [
      { titulo: 'Paso 1', descripcion: 'En la olla, dorá apenas el puerro.' },
      { titulo: 'Paso 2', descripcion: 'Agregá los arbolitos de brócoli y coliflor.' },
      { titulo: 'Paso 3', descripcion: 'Cubrí con el caldo y cociná 20 minutos hasta que estén súper tiernos.' },
      { titulo: 'Paso 4', descripcion: 'Procesá con fuerza hasta que se integren por completo formando una crema espesa.' },
    ],
  },
  {
    id: 55,
    numero: '55',
    nombre: 'Sopa Crema de Espinaca y Puerro Dulce',
    subtitulo: 'Nutrición reconfortante',
    categoria_sopa: 'Cremosas Livianas',
    caldo_base_sugerido_id: 2,
    porciones: '4',
    porcionesBase: 4,
    ingredientes: [
      { categoria: 'Verdulería', nombre: 'Espinaca fresca lavada sin tallos duros', cantidad_base: 2, unidad: 'atados' },
      { categoria: 'Verdulería', nombre: 'Puerros grandes en rodajitas finas', cantidad_base: 3, unidad: 'un' },
      { categoria: 'Preparaciones base', nombre: 'Caldo Base de Huesos', cantidad_base: 1, unidad: 'litro' },
    ],
    pasos_preparacion: [
      { titulo: 'Paso 1', descripcion: 'Rehogá los puerros a fuego mínimo hasta que estén transparentes y muy dulces (unos 10 minutos).' },
      { titulo: 'Paso 2', descripcion: 'Agregá el caldo y llevá a hervor.' },
      { titulo: 'Paso 3', descripcion: 'Sumá toda la espinaca fresca a la olla, tapá y apagá el fuego.' },
      { titulo: 'Paso 4', descripcion: 'Dejá reposar 3 minutos y procesá inmediatamente para atrapar el color y la textura cremosa.' },
    ],
  },
  {
    id: 56,
    numero: '56',
    nombre: 'Crema de Remolacha y Zanahoria',
    subtitulo: 'Color vibrante',
    categoria_sopa: 'Cremosas Livianas',
    caldo_base_sugerido_id: 1,
    porciones: '3',
    porcionesBase: 3,
    ingredientes: [
      { categoria: 'Verdulería', nombre: 'Remolacha chica pelada en cubitos', cantidad_base: 1, unidad: 'un' },
      { categoria: 'Verdulería', nombre: 'Zanahorias en rueditas', cantidad_base: 3, unidad: 'un' },
      { categoria: 'Verdulería', nombre: 'Cebolla blanca', cantidad_base: 1, unidad: 'un' },
      { categoria: 'Preparaciones base', nombre: 'Caldo Base de Vegetales', cantidad_base: 1, unidad: 'litro' },
    ],
    pasos_preparacion: [
      { titulo: 'Paso 1', descripcion: 'Rehogá la cebolla.' },
      { titulo: 'Paso 2', descripcion: 'Agregá la zanahoria y la remolacha.' },
      { titulo: 'Paso 3', descripcion: 'Volcá el caldo y herví por 25 minutos (la remolacha tiene que estar blanda).' },
      { titulo: 'Paso 4', descripcion: 'Procesá muy bien hasta lograr una crema fucsia homogénea.' },
    ],
  },
  {
    id: 57,
    numero: '57',
    nombre: 'Sopa Sedosa de Ajo Asado y Zapallo Anco',
    subtitulo: 'Aroma profundo',
    categoria_sopa: 'Cremosas Livianas',
    caldo_base_sugerido_id: 1,
    porciones: '3',
    porcionesBase: 3,
    ingredientes: [
      { categoria: 'Verdulería', nombre: 'Zapallo anco en cubos', cantidad_base: 0.5, unidad: 'un' },
      { categoria: 'Verdulería', nombre: 'Ajo asado', cantidad_base: 1, unidad: 'cabeza' },
      { categoria: 'Verdulería', nombre: 'Cebolla blanca', cantidad_base: 1, unidad: 'un' },
      { categoria: 'Preparaciones base', nombre: 'Caldo Base de Vegetales', cantidad_base: 1, unidad: 'litro' },
    ],
    pasos_preparacion: [
      { titulo: 'Paso 1', descripcion: 'Dorá la cebolla en la olla.' },
      { titulo: 'Paso 2', descripcion: 'Sumá los cubos de zapallo, el puré de ajo asado dulce y volcá el caldo.' },
      { titulo: 'Paso 3', descripcion: 'Cociná 20 minutos a fuego medio.' },
      { titulo: 'Paso 4', descripcion: 'Procesá con licuadora o minipimer hasta que no quede ningún grumo.' },
    ],
  },
  {
    id: 58,
    numero: '58',
    nombre: 'Crema de Morrón Asado y Zapallo Anco',
    subtitulo: 'Ahumado y dulzor',
    categoria_sopa: 'Cremosas Livianas',
    caldo_base_sugerido_id: 2,
    porciones: '3',
    porcionesBase: 3,
    ingredientes: [
      { categoria: 'Verdulería', nombre: 'Morrón rojo grande asado', cantidad_base: 1, unidad: 'un' },
      { categoria: 'Verdulería', nombre: 'Zapallo anco en cubos', cantidad_base: 0.5, unidad: 'un' },
      { categoria: 'Verdulería', nombre: 'Cebolla blanca', cantidad_base: 1, unidad: 'un' },
      { categoria: 'Preparaciones base', nombre: 'Caldo Base de Huesos', cantidad_base: 1, unidad: 'litro' },
    ],
    pasos_preparacion: [
      { titulo: 'Paso 1', descripcion: 'Rehogá la cebolla en la olla.' },
      { titulo: 'Paso 2', descripcion: 'Agregá el zapallo en cubos y el morrón asado cortado en tiras.' },
      { titulo: 'Paso 3', descripcion: 'Cubrí con el caldo y cociná 20 minutos.' },
      { titulo: 'Paso 4', descripcion: 'Procesá todo hasta que quede una crema naranja intensa y aromática.' },
    ],
  },
  {
    id: 59,
    numero: '59',
    nombre: 'Sopa de Puerro, Apio y Zanahoria',
    subtitulo: 'Sedosidad aromática',
    categoria_sopa: 'Cremosas Livianas',
    caldo_base_sugerido_id: 1,
    porciones: '3',
    porcionesBase: 3,
    ingredientes: [
      { categoria: 'Verdulería', nombre: 'Puerros grandes picados', cantidad_base: 2, unidad: 'un' },
      { categoria: 'Verdulería', nombre: 'Apio picado fino', cantidad_base: 3, unidad: 'ramas' },
      { categoria: 'Verdulería', nombre: 'Zanahorias grandes en ruedas', cantidad_base: 3, unidad: 'un' },
      { categoria: 'Preparaciones base', nombre: 'Caldo Base de Vegetales', cantidad_base: 1, unidad: 'litro' },
    ],
    pasos_preparacion: [
      { titulo: 'Paso 1', descripcion: 'Rehogá los tres vegetales juntos a fuego lento por 10 minutos para que suelten sus aromas.' },
      { titulo: 'Paso 2', descripcion: 'Agregá el caldo caliente.' },
      { titulo: 'Paso 3', descripcion: 'Cociná por 20 minutos más.' },
      { titulo: 'Paso 4', descripcion: 'Procesá a máxima potencia para romper bien la fibra del apio y que quede sedosa.' },
    ],
  },
  {
    id: 60,
    numero: '60',
    nombre: 'Crema de Repollo Blanco y Puerro',
    subtitulo: 'La gran sorpresa',
    categoria_sopa: 'Cremosas Livianas',
    caldo_base_sugerido_id: 1,
    porciones: '4',
    porcionesBase: 4,
    ingredientes: [
      { categoria: 'Verdulería', nombre: 'Repollo blanco cortado en tiras', cantidad_base: 0.5, unidad: 'un' },
      { categoria: 'Verdulería', nombre: 'Puerros grandes picados', cantidad_base: 2, unidad: 'un' },
      { categoria: 'Preparaciones base', nombre: 'Caldo Base de Vegetales', cantidad_base: 1, unidad: 'litro' },
    ],
    pasos_preparacion: [
      { titulo: 'Paso 1', descripcion: 'Dorá el puerro lentamente.' },
      { titulo: 'Paso 2', descripcion: 'Agregá el repollo y revolvé hasta que se achique un poco.' },
      { titulo: 'Paso 3', descripcion: 'Volcá el caldo y cociná a fuego lento por 30 minutos (el repollo tiene que estar súper blando y translúcido).' },
      { titulo: 'Paso 4', descripcion: 'Procesá muy bien. Te vas a sorprender con la textura blanca y pesada que se forma.' },
    ],
  },
];
